export const DEFAULT_CHAR_WIDTH = 8;
export const DEFAULT_LINE_HEIGHT = 27.3;

export const FILE_UPLOAD_ID_EDIT_PROFILE = 'FILE_UPLOAD_ID_EDIT_PROFILE';

export const FILE_UPLOAD_ID_ROOM_AVATAR_PREFIX = 'RA_';
export const FILE_UPLOAD_ID_ROOM_HISTORY_PREFIX = 'RH_';

export const ROOM_CREATE_SCREEN_TYPE_GROUP = 'CREATE_GROUP';
export const ROOM_CREATE_SCREEN_TYPE_CHANNEL = 'CREATE_CHANNEL';

export const APP_STATE_ACTIVE = 'active';
export const APP_STATE_BACKGROUND = 'background';
export const APP_STATE_INACTIVE = 'inactive';

export const APP_MODAL_ID_MAIN = 'APP_MODAL_ID_MAIN';
export const APP_MODAL_ID_PRIMARY = 'APP_MODAL_ID_PRIMARY';
export const APP_MODAL_ID_SECONDARY = 'APP_MODAL_ID_SECONDARY';

export const ROOM_MESSAGE_ATTACHMENT_TYPE_IMAGE = 'IMAGE';
export const ROOM_MESSAGE_ATTACHMENT_TYPE_VIDEO = 'VIDEO';
export const ROOM_MESSAGE_ATTACHMENT_TYPE_FILE = 'FILE';
export const ROOM_MESSAGE_ATTACHMENT_TYPE_AUDIO = 'AUDIO';
export const ROOM_MESSAGE_ATTACHMENT_TYPE_VOICE = 'VOICE';

export const ROOM_MESSAGE_ACTION_REPLY = 'reply';
export const ROOM_MESSAGE_ACTION_FORWARD = 'forward';
export const ROOM_MESSAGE_ACTION_DELETE = 'delete';
export const ROOM_MESSAGE_ACTION_REPORT = 'report';
export const ROOM_MESSAGE_ACTION_EDIT = 'edit';

export const SOUND_PLAYER_BOX_MESSAGE = 'SP_BOX_MESSAGE';
export const SOUND_PLAYER_BOX_TOOLBAR = 'SP_BOX_TOOLBAR';

export const MAP_DEFAULT_LATITUDE = 37.78825;
export const MAP_DEFAULT_LONGITUDE = -122.4324;

export const MAP_LATITUDE_DELTA = 0.04;
export const MAP_LONGITUDE_DELTA = 0.04;

export const NOTIFICATION_CHANNEL_ID = 'iGap-Plus-Channel';