export const FILE_UPLOAD_ID_EDIT_PROFILE = 'FILE_UPLOAD_ID_EDIT_PROFILE';

export const FILE_UPLOAD_ID_ROOM_AVATAR_PREFIX = 'RA_';

export const ROOM_CREATE_SCREEN_TYPE_GROUP = 'GROUP';
export const ROOM_CREATE_SCREEN_TYPE_CHANNEL = 'CHANNEL';
