export const FILE_UPLOAD_ID_EDIT_PROFILE = 'FILE_UPLOAD_ID_EDIT_PROFILE';

export const FILE_UPLOAD_ID_ROOM_AVATAR_PREFIX = 'RA_';
export const FILE_UPLOAD_ID_ROOM_HISTORY_PREFIX = 'RH_';

export const ROOM_CREATE_SCREEN_TYPE_GROUP = 'CREATE_GROUP';
export const ROOM_CREATE_SCREEN_TYPE_CHANNEL = 'CREATE_CHANNEL';

export const APP_MODAL_ID_MAIN = 'APP_MODAL_ID_MAIN';
export const APP_MODAL_ID_PRIMARY = 'APP_MODAL_ID_PRIMARY';
export const APP_MODAL_ID_SECONDARY = 'APP_MODAL_ID_SECONDARY';

export const ROOM_MESSAGE_ATTACHMENT_TYPE_IMAGE = 'IMAGE';
export const ROOM_MESSAGE_ATTACHMENT_TYPE_VIDEO = 'VIDEO';
export const ROOM_MESSAGE_ATTACHMENT_TYPE_FILE = 'FILE';
export const ROOM_MESSAGE_ATTACHMENT_TYPE_AUDIO = 'AUDIO';