/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var Request_pb = require('./Request_pb.js');
var Response_pb = require('./Response_pb.js');
goog.exportSymbol('proto.proto.ChannelGetMessagesStats', null, global);
goog.exportSymbol('proto.proto.ChannelGetMessagesStatsResponse', null, global);
goog.exportSymbol('proto.proto.ChannelGetMessagesStatsResponse.Stats', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.ChannelGetMessagesStats = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.proto.ChannelGetMessagesStats.repeatedFields_, null);
};
goog.inherits(proto.proto.ChannelGetMessagesStats, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.proto.ChannelGetMessagesStats.displayName = 'proto.proto.ChannelGetMessagesStats';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.proto.ChannelGetMessagesStats.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.ChannelGetMessagesStats.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.ChannelGetMessagesStats.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.ChannelGetMessagesStats} msg The msg instance to transform.
 * @return {!Object}
 */
proto.proto.ChannelGetMessagesStats.toObject = function(includeInstance, msg) {
  var f, obj = {
    request: (f = msg.getRequest()) && Request_pb.Request.toObject(includeInstance, f),
    roomId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    messageIdList: jspb.Message.getField(msg, 3)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.ChannelGetMessagesStats}
 */
proto.proto.ChannelGetMessagesStats.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.ChannelGetMessagesStats;
  return proto.proto.ChannelGetMessagesStats.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.ChannelGetMessagesStats} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.ChannelGetMessagesStats}
 */
proto.proto.ChannelGetMessagesStats.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new Request_pb.Request;
      reader.readMessage(value,Request_pb.Request.deserializeBinaryFromReader);
      msg.setRequest(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setRoomId(value);
      break;
    case 3:
      var value = /** @type {!Array.<number>} */ (reader.readPackedUint64());
      msg.setMessageIdList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.ChannelGetMessagesStats.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.ChannelGetMessagesStats.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.ChannelGetMessagesStats} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.proto.ChannelGetMessagesStats.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequest();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      Request_pb.Request.serializeBinaryToWriter
    );
  }
  f = message.getRoomId();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getMessageIdList();
  if (f.length > 0) {
    writer.writePackedUint64(
      3,
      f
    );
  }
};


/**
 * optional Request request = 1;
 * @return {?proto.proto.Request}
 */
proto.proto.ChannelGetMessagesStats.prototype.getRequest = function() {
  return /** @type{?proto.proto.Request} */ (
    jspb.Message.getWrapperField(this, Request_pb.Request, 1));
};


/** @param {?proto.proto.Request|undefined} value */
proto.proto.ChannelGetMessagesStats.prototype.setRequest = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.proto.ChannelGetMessagesStats.prototype.clearRequest = function() {
  this.setRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.ChannelGetMessagesStats.prototype.hasRequest = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional uint64 room_id = 2;
 * @return {number}
 */
proto.proto.ChannelGetMessagesStats.prototype.getRoomId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.proto.ChannelGetMessagesStats.prototype.setRoomId = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * repeated uint64 message_id = 3;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<number>}
 */
proto.proto.ChannelGetMessagesStats.prototype.getMessageIdList = function() {
  return /** @type {!Array.<number>} */ (jspb.Message.getField(this, 3));
};


/** @param {!Array.<number>} value */
proto.proto.ChannelGetMessagesStats.prototype.setMessageIdList = function(value) {
  jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.proto.ChannelGetMessagesStats.prototype.addMessageId = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


proto.proto.ChannelGetMessagesStats.prototype.clearMessageIdList = function() {
  this.setMessageIdList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.ChannelGetMessagesStatsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.proto.ChannelGetMessagesStatsResponse.repeatedFields_, null);
};
goog.inherits(proto.proto.ChannelGetMessagesStatsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.proto.ChannelGetMessagesStatsResponse.displayName = 'proto.proto.ChannelGetMessagesStatsResponse';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.proto.ChannelGetMessagesStatsResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.ChannelGetMessagesStatsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.ChannelGetMessagesStatsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.ChannelGetMessagesStatsResponse} msg The msg instance to transform.
 * @return {!Object}
 */
proto.proto.ChannelGetMessagesStatsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    response: (f = msg.getResponse()) && Response_pb.Response.toObject(includeInstance, f),
    statsList: jspb.Message.toObjectList(msg.getStatsList(),
    proto.proto.ChannelGetMessagesStatsResponse.Stats.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.ChannelGetMessagesStatsResponse}
 */
proto.proto.ChannelGetMessagesStatsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.ChannelGetMessagesStatsResponse;
  return proto.proto.ChannelGetMessagesStatsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.ChannelGetMessagesStatsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.ChannelGetMessagesStatsResponse}
 */
proto.proto.ChannelGetMessagesStatsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new Response_pb.Response;
      reader.readMessage(value,Response_pb.Response.deserializeBinaryFromReader);
      msg.setResponse(value);
      break;
    case 2:
      var value = new proto.proto.ChannelGetMessagesStatsResponse.Stats;
      reader.readMessage(value,proto.proto.ChannelGetMessagesStatsResponse.Stats.deserializeBinaryFromReader);
      msg.addStats(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.ChannelGetMessagesStatsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.ChannelGetMessagesStatsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.ChannelGetMessagesStatsResponse} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.proto.ChannelGetMessagesStatsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResponse();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      Response_pb.Response.serializeBinaryToWriter
    );
  }
  f = message.getStatsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.proto.ChannelGetMessagesStatsResponse.Stats.serializeBinaryToWriter
    );
  }
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.ChannelGetMessagesStatsResponse.Stats = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proto.ChannelGetMessagesStatsResponse.Stats, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.proto.ChannelGetMessagesStatsResponse.Stats.displayName = 'proto.proto.ChannelGetMessagesStatsResponse.Stats';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.ChannelGetMessagesStatsResponse.Stats.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.ChannelGetMessagesStatsResponse.Stats.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.ChannelGetMessagesStatsResponse.Stats} msg The msg instance to transform.
 * @return {!Object}
 */
proto.proto.ChannelGetMessagesStatsResponse.Stats.toObject = function(includeInstance, msg) {
  var f, obj = {
    messageId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    viewsLabel: jspb.Message.getFieldWithDefault(msg, 2, ""),
    thumbsUpLabel: jspb.Message.getFieldWithDefault(msg, 3, ""),
    thumbsDownLabel: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.ChannelGetMessagesStatsResponse.Stats}
 */
proto.proto.ChannelGetMessagesStatsResponse.Stats.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.ChannelGetMessagesStatsResponse.Stats;
  return proto.proto.ChannelGetMessagesStatsResponse.Stats.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.ChannelGetMessagesStatsResponse.Stats} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.ChannelGetMessagesStatsResponse.Stats}
 */
proto.proto.ChannelGetMessagesStatsResponse.Stats.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setMessageId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setViewsLabel(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setThumbsUpLabel(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setThumbsDownLabel(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.ChannelGetMessagesStatsResponse.Stats.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.ChannelGetMessagesStatsResponse.Stats.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.ChannelGetMessagesStatsResponse.Stats} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.proto.ChannelGetMessagesStatsResponse.Stats.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessageId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getViewsLabel();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getThumbsUpLabel();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getThumbsDownLabel();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional uint64 message_id = 1;
 * @return {number}
 */
proto.proto.ChannelGetMessagesStatsResponse.Stats.prototype.getMessageId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.proto.ChannelGetMessagesStatsResponse.Stats.prototype.setMessageId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string views_label = 2;
 * @return {string}
 */
proto.proto.ChannelGetMessagesStatsResponse.Stats.prototype.getViewsLabel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.proto.ChannelGetMessagesStatsResponse.Stats.prototype.setViewsLabel = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string thumbs_up_label = 3;
 * @return {string}
 */
proto.proto.ChannelGetMessagesStatsResponse.Stats.prototype.getThumbsUpLabel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.proto.ChannelGetMessagesStatsResponse.Stats.prototype.setThumbsUpLabel = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string thumbs_down_label = 4;
 * @return {string}
 */
proto.proto.ChannelGetMessagesStatsResponse.Stats.prototype.getThumbsDownLabel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.proto.ChannelGetMessagesStatsResponse.Stats.prototype.setThumbsDownLabel = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional Response response = 1;
 * @return {?proto.proto.Response}
 */
proto.proto.ChannelGetMessagesStatsResponse.prototype.getResponse = function() {
  return /** @type{?proto.proto.Response} */ (
    jspb.Message.getWrapperField(this, Response_pb.Response, 1));
};


/** @param {?proto.proto.Response|undefined} value */
proto.proto.ChannelGetMessagesStatsResponse.prototype.setResponse = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.proto.ChannelGetMessagesStatsResponse.prototype.clearResponse = function() {
  this.setResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.ChannelGetMessagesStatsResponse.prototype.hasResponse = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Stats stats = 2;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.proto.ChannelGetMessagesStatsResponse.Stats>}
 */
proto.proto.ChannelGetMessagesStatsResponse.prototype.getStatsList = function() {
  return /** @type{!Array.<!proto.proto.ChannelGetMessagesStatsResponse.Stats>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.proto.ChannelGetMessagesStatsResponse.Stats, 2));
};


/** @param {!Array.<!proto.proto.ChannelGetMessagesStatsResponse.Stats>} value */
proto.proto.ChannelGetMessagesStatsResponse.prototype.setStatsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.proto.ChannelGetMessagesStatsResponse.Stats=} opt_value
 * @param {number=} opt_index
 * @return {!proto.proto.ChannelGetMessagesStatsResponse.Stats}
 */
proto.proto.ChannelGetMessagesStatsResponse.prototype.addStats = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.proto.ChannelGetMessagesStatsResponse.Stats, opt_index);
};


proto.proto.ChannelGetMessagesStatsResponse.prototype.clearStatsList = function() {
  this.setStatsList([]);
};


goog.object.extend(exports, proto.proto);
