/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var Request_pb = require('./Request_pb.js');
var Response_pb = require('./Response_pb.js');
goog.exportSymbol('proto.proto.UserTwoStepVerificationGetPasswordDetail', null, global);
goog.exportSymbol('proto.proto.UserTwoStepVerificationGetPasswordDetailResponse', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.UserTwoStepVerificationGetPasswordDetail = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proto.UserTwoStepVerificationGetPasswordDetail, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.proto.UserTwoStepVerificationGetPasswordDetail.displayName = 'proto.proto.UserTwoStepVerificationGetPasswordDetail';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.UserTwoStepVerificationGetPasswordDetail.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.UserTwoStepVerificationGetPasswordDetail.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.UserTwoStepVerificationGetPasswordDetail} msg The msg instance to transform.
 * @return {!Object}
 */
proto.proto.UserTwoStepVerificationGetPasswordDetail.toObject = function(includeInstance, msg) {
  var f, obj = {
    request: (f = msg.getRequest()) && Request_pb.Request.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.UserTwoStepVerificationGetPasswordDetail}
 */
proto.proto.UserTwoStepVerificationGetPasswordDetail.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.UserTwoStepVerificationGetPasswordDetail;
  return proto.proto.UserTwoStepVerificationGetPasswordDetail.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.UserTwoStepVerificationGetPasswordDetail} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.UserTwoStepVerificationGetPasswordDetail}
 */
proto.proto.UserTwoStepVerificationGetPasswordDetail.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new Request_pb.Request;
      reader.readMessage(value,Request_pb.Request.deserializeBinaryFromReader);
      msg.setRequest(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.UserTwoStepVerificationGetPasswordDetail.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.UserTwoStepVerificationGetPasswordDetail.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.UserTwoStepVerificationGetPasswordDetail} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.proto.UserTwoStepVerificationGetPasswordDetail.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequest();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      Request_pb.Request.serializeBinaryToWriter
    );
  }
};


/**
 * optional Request request = 1;
 * @return {?proto.proto.Request}
 */
proto.proto.UserTwoStepVerificationGetPasswordDetail.prototype.getRequest = function() {
  return /** @type{?proto.proto.Request} */ (
    jspb.Message.getWrapperField(this, Request_pb.Request, 1));
};


/** @param {?proto.proto.Request|undefined} value */
proto.proto.UserTwoStepVerificationGetPasswordDetail.prototype.setRequest = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.proto.UserTwoStepVerificationGetPasswordDetail.prototype.clearRequest = function() {
  this.setRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.UserTwoStepVerificationGetPasswordDetail.prototype.hasRequest = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.UserTwoStepVerificationGetPasswordDetailResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proto.UserTwoStepVerificationGetPasswordDetailResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.proto.UserTwoStepVerificationGetPasswordDetailResponse.displayName = 'proto.proto.UserTwoStepVerificationGetPasswordDetailResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.UserTwoStepVerificationGetPasswordDetailResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.UserTwoStepVerificationGetPasswordDetailResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.UserTwoStepVerificationGetPasswordDetailResponse} msg The msg instance to transform.
 * @return {!Object}
 */
proto.proto.UserTwoStepVerificationGetPasswordDetailResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    response: (f = msg.getResponse()) && Response_pb.Response.toObject(includeInstance, f),
    questionOne: jspb.Message.getFieldWithDefault(msg, 2, ""),
    questionTwo: jspb.Message.getFieldWithDefault(msg, 3, ""),
    hint: jspb.Message.getFieldWithDefault(msg, 4, ""),
    hasConfirmedRecoveryEmail: jspb.Message.getFieldWithDefault(msg, 5, false),
    unconfirmedEmailPattern: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.UserTwoStepVerificationGetPasswordDetailResponse}
 */
proto.proto.UserTwoStepVerificationGetPasswordDetailResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.UserTwoStepVerificationGetPasswordDetailResponse;
  return proto.proto.UserTwoStepVerificationGetPasswordDetailResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.UserTwoStepVerificationGetPasswordDetailResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.UserTwoStepVerificationGetPasswordDetailResponse}
 */
proto.proto.UserTwoStepVerificationGetPasswordDetailResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new Response_pb.Response;
      reader.readMessage(value,Response_pb.Response.deserializeBinaryFromReader);
      msg.setResponse(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setQuestionOne(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setQuestionTwo(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setHint(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHasConfirmedRecoveryEmail(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setUnconfirmedEmailPattern(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.UserTwoStepVerificationGetPasswordDetailResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.UserTwoStepVerificationGetPasswordDetailResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.UserTwoStepVerificationGetPasswordDetailResponse} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.proto.UserTwoStepVerificationGetPasswordDetailResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResponse();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      Response_pb.Response.serializeBinaryToWriter
    );
  }
  f = message.getQuestionOne();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getQuestionTwo();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getHint();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getHasConfirmedRecoveryEmail();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getUnconfirmedEmailPattern();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional Response response = 1;
 * @return {?proto.proto.Response}
 */
proto.proto.UserTwoStepVerificationGetPasswordDetailResponse.prototype.getResponse = function() {
  return /** @type{?proto.proto.Response} */ (
    jspb.Message.getWrapperField(this, Response_pb.Response, 1));
};


/** @param {?proto.proto.Response|undefined} value */
proto.proto.UserTwoStepVerificationGetPasswordDetailResponse.prototype.setResponse = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.proto.UserTwoStepVerificationGetPasswordDetailResponse.prototype.clearResponse = function() {
  this.setResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.UserTwoStepVerificationGetPasswordDetailResponse.prototype.hasResponse = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string question_one = 2;
 * @return {string}
 */
proto.proto.UserTwoStepVerificationGetPasswordDetailResponse.prototype.getQuestionOne = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.proto.UserTwoStepVerificationGetPasswordDetailResponse.prototype.setQuestionOne = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string question_two = 3;
 * @return {string}
 */
proto.proto.UserTwoStepVerificationGetPasswordDetailResponse.prototype.getQuestionTwo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.proto.UserTwoStepVerificationGetPasswordDetailResponse.prototype.setQuestionTwo = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string hint = 4;
 * @return {string}
 */
proto.proto.UserTwoStepVerificationGetPasswordDetailResponse.prototype.getHint = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.proto.UserTwoStepVerificationGetPasswordDetailResponse.prototype.setHint = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional bool has_confirmed_recovery_email = 5;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.proto.UserTwoStepVerificationGetPasswordDetailResponse.prototype.getHasConfirmedRecoveryEmail = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 5, false));
};


/** @param {boolean} value */
proto.proto.UserTwoStepVerificationGetPasswordDetailResponse.prototype.setHasConfirmedRecoveryEmail = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional string unconfirmed_email_pattern = 6;
 * @return {string}
 */
proto.proto.UserTwoStepVerificationGetPasswordDetailResponse.prototype.getUnconfirmedEmailPattern = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.proto.UserTwoStepVerificationGetPasswordDetailResponse.prototype.setUnconfirmedEmailPattern = function(value) {
  jspb.Message.setField(this, 6, value);
};


goog.object.extend(exports, proto.proto);
