/**
 * @flow
 */

// System errors xx

export const ERROR_BAD_REQUEST = 1;
export const ERROR_LOGIN_REQUIRED = 2;
export const ERROR_NEW_CLIENT_IN_SESSION = 3;
export const ERROR_FORBIDDEN = 4;
export const ERROR_TIMEOUT = 5;
export const ERROR_RELATION_ERROR = 6;
export const ERROR_INTERNAL_SERVER_ERROR = 7;
export const ERROR_SESSION_IS_TERMINATED = 8;
export const ERROR_NICKNAME_REQUIRED = 9;
export const ERROR_FLOOD_REQUEST = 10;

// User errors 1xx , 101xx

export const ERROR_USER_REGISTER_BAD_PAYLOAD = 100;
export const ERROR_USER_REGISTER_INTERNAL_SERVER_ERROR = 101;
export const ERROR_USER_REGISTER_BLOCKED_USER = 135;
export const ERROR_USER_REGISTER_MAX_TRY_LOCK = 136;
export const ERROR_USER_REGISTER_MAX_SEND_LOCK = 137;

export const ERROR_USER_VERIFY_BAD_PAYLOAD = 102;
export const ERROR_USER_VERIFY_INTERNAL_SERVER_ERROR = 103;
export const ERROR_USER_VERIFY_USER_NOT_FOUND = 104;
export const ERROR_USER_VERIFY_BLOCKED_USER = 105;
export const ERROR_USER_VERIFY_INVALID_CODE = 106;
export const ERROR_USER_VERIFY_EXPIRED_CODE = 107;
export const ERROR_USER_VERIFY_MAX_TRY_LOCK = 108;
export const ERROR_USER_VERIFY_TWO_STEP_VERIFICATION_ENABLED = 184;

export const ERROR_USER_LOGIN_BAD_PAYLOAD = 109;
export const ERROR_USER_LOGIN_INTERNAL_SERVER_ERROR = 110;
export const ERROR_USER_LOGIN_FAILED = 111;
export const ERROR_USER_LOGIN_ALREADY_LOGGED_IN = 10170;

export const ERROR_USER_PROFILE_SET_NICKNAME_BAD_PAYLOAD = 112;
export const ERROR_USER_PROFILE_SET_NICKNAME_INTERNAL_SERVER_ERROR = 113;

export const ERROR_USER_PROFILE_SET_EMAIL_BAD_PAYLOAD = 114;
export const ERROR_USER_PROFILE_SET_EMAIL_INTERNAL_SERVER_ERROR = 115;

export const ERROR_USER_PROFILE_SET_GENDER_BAD_PAYLOAD = 116;
export const ERROR_USER_PROFILE_SET_GENDER_INTERNAL_SERVER_ERROR = 117;

export const ERROR_USER_CONTACTS_IMPORT_BAD_PAYLOAD = 118;
export const ERROR_USER_CONTACTS_IMPORT_INTERNAL_SERVER_ERROR = 119;
export const ERROR_USER_CONTACTS_IMPORT_FORBIDDEN = 10169;

export const ERROR_USER_CONTACTS_GET_LIST_BAD_PAYLOAD = 120;
export const ERROR_USER_CONTACTS_GET_LIST_INTERNAL_SERVER_ERROR = 121;

export const ERROR_USER_CONTACTS_DELETE_BAD_PAYLOAD = 122;
export const ERROR_USER_CONTACTS_DELETE_INTERNAL_SERVER_ERROR = 123;

export const ERROR_USER_CONTACTS_EDIT_BAD_PAYLOAD = 124;
export const ERROR_USER_CONTACTS_EDIT_INTERNAL_SERVER_ERROR = 125;

export const ERROR_USER_PROFILE_GET_NICKNAME_BAD_PAYLOAD = 126;
export const ERROR_USER_PROFILE_GET_NICKNAME_INTERNAL_SERVER_ERROR = 127;

export const ERROR_USER_PROFILE_GET_EMAIL_BAD_PAYLOAD = 128;
export const ERROR_USER_PROFILE_GET_EMAIL_INTERNAL_SERVER_ERROR = 129;

export const ERROR_USER_PROFILE_GET_GENDER_BAD_PAYLOAD = 130;
export const ERROR_USER_PROFILE_GET_GENDER_INTERNAL_SERVER_ERROR = 131;

export const ERROR_USER_AVATAR_ADD_BAD_PAYLOAD = 138;
export const ERROR_USER_AVATAR_ADD_INTERNAL_SERVER_ERROR = 139;
export const ERROR_USER_AVATAR_ADD_FORBIDDEN = 140;

export const ERROR_USER_AVATAR_DELETE_BAD_PAYLOAD = 141;
export const ERROR_USER_AVATAR_DELETE_INTERNAL_SERVER_ERROR = 142;
export const ERROR_USER_AVATAR_DELETE_FORBIDDEN = 143;

export const ERROR_USER_AVATAR_GET_LIST_BAD_PAYLOAD = 144;
export const ERROR_USER_AVATAR_GET_LIST_INTERNAL_SERVER_ERROR = 145;
export const ERROR_USER_AVATAR_GET_LIST_FORBIDDEN = 146;

export const ERROR_USER_INFO_BAD_PAYLOAD = 147;
export const ERROR_USER_INFO_INTERNAL_SERVER_ERROR = 148;
export const ERROR_USER_INFO_FORBIDDEN = 149;

export const ERROR_USER_GET_DELETE_TOKEN_BAD_PAYLOAD = 150;
export const ERROR_USER_GET_DELETE_TOKEN_INTERNAL_SERVER_ERROR = 151;
export const ERROR_USER_GET_DELETE_TOKEN_MAX_TRY_LOCK = 152;
export const ERROR_USER_GET_DELETE_TOKEN_MAX_SEND_LOCK = 153;

export const ERROR_USER_DELETE_BAD_PAYLOAD = 154;
export const ERROR_USER_DELETE_INTERNAL_SERVER_ERROR = 155;
export const ERROR_USER_DELETE_INVALID_TOKEN = 156;
export const ERROR_USER_DELETE_EXPIRED_TOKEN = 157;
export const ERROR_USER_DELETE_MAX_TRY_LOCK = 158;

export const ERROR_USER_PROFILE_GET_SELF_REMOVE_BAD_PAYLOAD = 159;
export const ERROR_USER_PROFILE_GET_SELF_REMOVE_INTERNAL_SERVER_ERROR = 160;

export const ERROR_USER_PROFILE_SET_SELF_REMOVE_BAD_PAYLOAD = 161;
export const ERROR_USER_PROFILE_SET_SELF_REMOVE_INTERNAL_SERVER_ERROR = 162;

export const ERROR_USER_PROFILE_CHECK_USERNAME_INTERNAL_SERVER_ERROR = 163;

export const ERROR_USER_PROFILE_UPDATE_USERNAME_BAD_PAYLOAD = 164;
export const ERROR_USER_PROFILE_UPDATE_USERNAME_INTERNAL_SERVER_ERROR = 165;
export const ERROR_USER_PROFILE_UPDATE_USERNAME_UPDATE_LOCK = 175;

export const ERROR_USER_UPDATE_STATUS_BAD_PAYLOAD = 166;
export const ERROR_USER_UPDATE_STATUS_INTERNAL_SERVER_ERROR = 167;

export const ERROR_USER_SESSION_GET_ACTIVE_LIST_BAD_PAYLOAD = 168;
export const ERROR_USER_SESSION_GET_ACTIVE_LIST_INTERNAL_SERVER_ERROR = 169;

export const ERROR_USER_SESSION_TERMINATE_BAD_PAYLOAD = 170;
export const ERROR_USER_SESSION_TERMINATE_INTERNAL_SERVER_ERROR = 171;
export const ERROR_USER_SESSION_TERMINATE_FORBIDDEN = 172;

export const ERROR_USER_SESSION_LOGOUT_BAD_PAYLOAD = 173;
export const ERROR_USER_SESSION_LOGOUT_INTERNAL_SERVER_ERROR = 174;

export const ERROR_USER_CONTACTS_BLOCK_BAD_PAYLOAD = 176;
export const ERROR_USER_CONTACTS_BLOCK_INTERNAL_SERVER_ERROR = 177;
export const ERROR_USER_CONTACTS_BLOCK_USER_NOT_FOUND = 178;

export const ERROR_USER_CONTACTS_UNBLOCK_BAD_PAYLOAD = 179;
export const ERROR_USER_CONTACTS_UNBLOCK_INTERNAL_SERVER_ERROR = 180;
export const ERROR_USER_CONTACTS_UNBLOCK_ALREADY_UNBLOCKED = 181;

export const ERROR_USER_CONTACTS_GET_BLOCKED_LIST_BAD_PAYLOAD = 182;
export const ERROR_USER_CONTACTS_GET_BLOCKED_LIST_INTERNAL_SERVER_ERROR = 183;

export const ERROR_USER_TWO_STEP_VERIFICATION_GET_PASSWORD_DETAIL_BAD_PAYLOAD = 185;
export const ERROR_USER_TWO_STEP_VERIFICATION_GET_PASSWORD_DETAIL_INTERNAL_SERVER_ERROR = 186;
export const ERROR_USER_TWO_STEP_VERIFICATION_GET_PASSWORD_DETAIL_FORBIDDEN = 187;
export const ERROR_USER_TWO_STEP_VERIFICATION_GET_PASSWORD_DETAIL_NO_PASSWORD = 188;

export const ERROR_USER_TWO_STEP_VERIFICATION_VERIFY_PASSWORD_BAD_PAYLOAD = 189;
export const ERROR_USER_TWO_STEP_VERIFICATION_VERIFY_PASSWORD_INTERNAL_SERVER_ERROR = 190;
export const ERROR_USER_TWO_STEP_VERIFICATION_VERIFY_PASSWORD_MAX_TRY_LOCK = 191;
export const ERROR_USER_TWO_STEP_VERIFICATION_VERIFY_PASSWORD_FORBIDDEN = 192;
export const ERROR_USER_TWO_STEP_VERIFICATION_VERIFY_PASSWORD_NO_PASSWORD = 193;
export const ERROR_USER_TWO_STEP_VERIFICATION_VERIFY_PASSWORD_INVALID_PASSWORD = 194;

export const ERROR_USER_TWO_STEP_VERIFICATION_SET_PASSWORD_BAD_PAYLOAD = 195;
export const ERROR_USER_TWO_STEP_VERIFICATION_SET_PASSWORD_INTERNAL_SERVER_ERROR = 196;
export const ERROR_USER_TWO_STEP_VERIFICATION_SET_PASSWORD_MAX_TRY_LOCK = 197;
export const ERROR_USER_TWO_STEP_VERIFICATION_SET_PASSWORD_INVALID_OLD_PASSWORD = 198;

export const ERROR_USER_TWO_STEP_VERIFICATION_UNSET_PASSWORD_BAD_PAYLOAD = 199;
export const ERROR_USER_TWO_STEP_VERIFICATION_UNSET_PASSWORD_INTERNAL_SERVER_ERROR = 10100;
export const ERROR_USER_TWO_STEP_VERIFICATION_UNSET_PASSWORD_MAX_TRY_LOCK = 10101;
export const ERROR_USER_TWO_STEP_VERIFICATION_UNSET_PASSWORD_INVALID_PASSWORD = 10102;

export const ERROR_USER_TWO_STEP_VERIFICATION_CHECK_PASSWORD_BAD_PAYLOAD = 10103;
export const ERROR_USER_TWO_STEP_VERIFICATION_CHECK_PASSWORD_INTERNAL_SERVER_ERROR = 10104;
export const ERROR_USER_TWO_STEP_VERIFICATION_CHECK_PASSWORD_INVALID_PASSWORD = 10105;
export const ERROR_USER_TWO_STEP_VERIFICATION_CHECK_PASSWORD_MAX_TRY_LOCK = 10106;
export const ERROR_USER_TWO_STEP_VERIFICATION_CHECK_PASSWORD_NO_PASSWORD = 10107;

export const ERROR_USER_TWO_STEP_VERIFICATION_VERIFY_RECOVERY_EMAIL_BAD_PAYLOAD = 10108;
export const ERROR_USER_TWO_STEP_VERIFICATION_VERIFY_RECOVERY_EMAIL_INTERNAL_SERVER_ERROR = 10109;
export const ERROR_USER_TWO_STEP_VERIFICATION_VERIFY_RECOVERY_EMAIL_MAX_TRY_LOCK = 10110;
export const ERROR_USER_TWO_STEP_VERIFICATION_VERIFY_RECOVERY_EMAIL_EXPIRED_TOKEN = 10111;
export const ERROR_USER_TWO_STEP_VERIFICATION_VERIFY_RECOVERY_EMAIL_NO_PASSWORD = 10112;
export const ERROR_USER_TWO_STEP_VERIFICATION_VERIFY_RECOVERY_EMAIL_INVALID_TOKEN = 10113;

export const ERROR_USER_TWO_STEP_VERIFICATION_CHANGE_RECOVERY_EMAIL_BAD_PAYLOAD = 10114;
export const ERROR_USER_TWO_STEP_VERIFICATION_CHANGE_RECOVERY_EMAIL_INTERNAL_SERVER_ERROR = 10115;
export const ERROR_USER_TWO_STEP_VERIFICATION_CHANGE_RECOVERY_EMAIL_MAX_TRY_LOCK = 10116;
export const ERROR_USER_TWO_STEP_VERIFICATION_CHANGE_RECOVERY_EMAIL_NO_PASSWORD = 10117;
export const ERROR_USER_TWO_STEP_VERIFICATION_CHANGE_RECOVERY_EMAIL_INVALID_PASSWORD = 10118;
export const ERROR_USER_TWO_STEP_VERIFICATION_CHANGE_RECOVERY_EMAIL_CONFIRMED_BEFORE = 10119;

export const ERROR_USER_TWO_STEP_VERIFICATION_REQUEST_RECOVERY_TOKEN_BAD_PAYLOAD = 10120;
export const ERROR_USER_TWO_STEP_VERIFICATION_REQUEST_RECOVERY_TOKEN_INTERNAL_SERVER_ERROR = 10121;
export const ERROR_USER_TWO_STEP_VERIFICATION_REQUEST_RECOVERY_TOKEN_NO_PASSWORD = 10122;
export const ERROR_USER_TWO_STEP_VERIFICATION_REQUEST_RECOVERY_TOKEN_NO_RECOVERY_EMAIL = 10123;
export const ERROR_USER_TWO_STEP_VERIFICATION_REQUEST_RECOVERY_TOKEN_MAX_TRY_LOCK = 10124;
export const ERROR_USER_TWO_STEP_VERIFICATION_REQUEST_RECOVERY_TOKEN_FORBIDDEN = 10154;

export const ERROR_USER_TWO_STEP_VERIFICATION_RECOVER_PASSWORD_BY_TOKEN_BAD_PAYLOAD = 10125;
export const ERROR_USER_TWO_STEP_VERIFICATION_RECOVER_PASSWORD_BY_TOKEN_INTERNAL_SERVER_ERROR = 10126;
export const ERROR_USER_TWO_STEP_VERIFICATION_RECOVER_PASSWORD_BY_TOKEN_MAX_TRY_LOCK = 10127;
export const ERROR_USER_TWO_STEP_VERIFICATION_RECOVER_PASSWORD_BY_TOKEN_EXPIRED_TOKEN = 10128;
export const ERROR_USER_TWO_STEP_VERIFICATION_RECOVER_PASSWORD_BY_TOKEN_INVALID_TOKEN = 10129;
export const ERROR_USER_TWO_STEP_VERIFICATION_RECOVER_PASSWORD_BY_TOKEN_NO_PASSWORD = 10130;
export const ERROR_USER_TWO_STEP_VERIFICATION_RECOVER_PASSWORD_BY_TOKEN_FORBIDDEN = 10155;

export const ERROR_USER_TWO_STEP_VERIFICATION_RECOVER_PASSWORD_BY_ANSWERS_BAD_PAYLOAD = 10131;
export const ERROR_USER_TWO_STEP_VERIFICATION_RECOVER_PASSWORD_BY_ANSWERS_INTERNAL_SERVER_ERROR = 10132;
export const ERROR_USER_TWO_STEP_VERIFICATION_RECOVER_PASSWORD_BY_ANSWERS_MAX_TRY_LOCK = 10133;
export const ERROR_USER_TWO_STEP_VERIFICATION_RECOVER_PASSWORD_BY_ANSWERS_INVALID_ANSWERS = 10134;
export const ERROR_USER_TWO_STEP_VERIFICATION_RECOVER_PASSWORD_BY_ANSWERS_NO_PASSWORD = 10135;
export const ERROR_USER_TWO_STEP_VERIFICATION_RECOVER_PASSWORD_BY_ANSWERS_FORBIDDEN = 10156;

export const ERROR_USER_TWO_STEP_VERIFICATION_CHANGE_RECOVERY_QUESTION_BAD_PAYLOAD = 10136;
export const ERROR_USER_TWO_STEP_VERIFICATION_CHANGE_RECOVERY_QUESTION_INTERNAL_SERVER_ERROR = 10137;
export const ERROR_USER_TWO_STEP_VERIFICATION_CHANGE_RECOVERY_QUESTION_MAX_TRY_LOCK = 10138;
export const ERROR_USER_TWO_STEP_VERIFICATION_CHANGE_RECOVERY_QUESTION_NO_PASSWORD = 10139;
export const ERROR_USER_TWO_STEP_VERIFICATION_CHANGE_RECOVERY_QUESTION_INVALID_PASSWORD = 10140;

export const ERROR_USER_TWO_STEP_VERIFICATION_CHANGE_HINT_BAD_PAYLOAD = 10141;
export const ERROR_USER_TWO_STEP_VERIFICATION_CHANGE_HINT_INTERNAL_SERVER_ERROR = 10142;
export const ERROR_USER_TWO_STEP_VERIFICATION_CHANGE_HINT_MAX_TRY_LOCK = 10143;
export const ERROR_USER_TWO_STEP_VERIFICATION_CHANGE_HINT_NO_PASSWORD = 10144;
export const ERROR_USER_TWO_STEP_VERIFICATION_CHANGE_HINT_INVALID_PASSWORD = 10145;

export const ERROR_USER_TWO_STEP_VERIFICATION_RESEND_VERIFY_EMAIL_BAD_PAYLOAD = 10157;
export const ERROR_USER_TWO_STEP_VERIFICATION_RESEND_VERIFY_EMAIL_INTERNAL_SERVER_ERROR = 10158;
export const ERROR_USER_TWO_STEP_VERIFICATION_RESEND_VERIFY_EMAIL_NO_PASSWORD = 10159;
export const ERROR_USER_TWO_STEP_VERIFICATION_RESEND_VERIFY_EMAIL_NO_UNCONFIRMED_RECOVERY_EMAIL = 10160;

export const ERROR_USER_PRIVACY_GET_RULE_BAD_PAYLOAD = 10146;
export const ERROR_USER_PRIVACY_GET_RULE_INTERNAL_SERVER_ERROR = 10147;

export const ERROR_USER_PRIVACY_SET_RULE_BAD_PAYLOAD = 10148;
export const ERROR_USER_PRIVACY_SET_RULE_INTERNAL_SERVER_ERROR = 10149;

export const ERROR_USER_VERIFY_NEW_DEVICE_BAD_PAYLOAD = 10150;
export const ERROR_USER_VERIFY_NEW_DEVICE_INTERNAL_SERVER_ERROR = 10151;
export const ERROR_USER_VERIFY_NEW_DEVICE_INVALID_TOKEN = 10152;
export const ERROR_USER_VERIFY_NEW_DEVICE_EXPIRED_TOKEN = 10153;

export const ERROR_USER_PROFILE_SET_BIO_BAD_PAYLOAD = 10161;
export const ERROR_USER_PROFILE_SET_BIO_INTERNAL_SERVER_ERROR = 10162;

export const ERROR_USER_PROFILE_GET_BIO_BAD_PAYLOAD = 10163;
export const ERROR_USER_PROFILE_GET_BIO_INTERNAL_SERVER_ERROR = 10164;

export const ERROR_USER_REPORT_BAD_PAYLOAD = 10165;
export const ERROR_USER_REPORT_INTERNAL_SERVER_ERROR = 10166;
export const ERROR_USER_REPORT_REPORTED_BEFORE = 10167;
export const ERROR_USER_REPORT_FORBIDDEN = 10168;

// Chat room errors 2xx

export const ERROR_CHAT_GET_ROOM_BAD_PAYLOAD = 200;
export const ERROR_CHAT_GET_ROOM_INTERNAL_SERVER_ERROR = 201;
export const ERROR_CHAT_GET_ROOM_PEER_NOT_FOUND = 202;

export const ERROR_CHAT_SEND_MESSAGE_BAD_PAYLOAD = 203;
export const ERROR_CHAT_SEND_MESSAGE_INTERNAL_SERVER_ERROR = 204;
export const ERROR_CHAT_SEND_MESSAGE_FORBIDDEN = 205;
export const ERROR_CHAT_SEND_MESSAGE_BLOCKED_BY_PEER = 233;
export const ERROR_CHAT_SEND_MESSAGE_LIMIT_REACHED = 234;

export const ERROR_CHAT_UPDATE_STATUS_BAD_PAYLOAD = 206;
export const ERROR_CHAT_UPDATE_STATUS_INTERNAL_SERVER_ERROR = 207;
export const ERROR_CHAT_UPDATE_STATUS_FORBIDDEN = 208;

export const ERROR_CHAT_EDIT_MESSAGE_BAD_PAYLOAD = 209;
export const ERROR_CHAT_EDIT_MESSAGE_INTERNAL_SERVER_ERROR = 210;
export const ERROR_CHAT_EDIT_MESSAGE_FORBIDDEN = 211;

export const ERROR_CHAT_DELETE_MESSAGE_BAD_PAYLOAD = 212;
export const ERROR_CHAT_DELETE_MESSAGE_INTERNAL_SERVER_ERROR = 213;
export const ERROR_CHAT_DELETE_MESSAGE_FORBIDDEN = 214;

export const ERROR_CHAT_CLEAR_MESSAGE_BAD_PAYLOAD = 215;
export const ERROR_CHAT_CLEAR_MESSAGE_INTERNAL_SERVER_ERROR = 216;
export const ERROR_CHAT_CLEAR_MESSAGE_FORBIDDEN = 217;

export const ERROR_CHAT_DELETE_BAD_PAYLOAD = 218;
export const ERROR_CHAT_DELETE_INTERNAL_SERVER_ERROR = 219;
export const ERROR_CHAT_DELETE_FORBIDDEN = 220;

export const ERROR_CHAT_UPDATE_DRAFT_BAD_PAYLOAD = 221;
export const ERROR_CHAT_UPDATE_DRAFT_INTERNAL_SERVER_ERROR = 222;
export const ERROR_CHAT_UPDATE_DRAFT_FORBIDDEN = 223;

export const ERROR_CHAT_GET_DRAFT_BAD_PAYLOAD = 224;
export const ERROR_CHAT_GET_DRAFT_INTERNAL_SERVER_ERROR = 225;
export const ERROR_CHAT_GET_DRAFT_FORBIDDEN = 226;

export const ERROR_CHAT_CONVERT_TO_GROUP_BAD_PAYLOAD = 227;
export const ERROR_CHAT_CONVERT_TO_GROUP_INTERNAL_SERVER_ERROR = 228;
export const ERROR_CHAT_CONVERT_TO_GROUP_FORBIDDEN = 229;

export const ERROR_CHAT_SET_ACTION_BAD_PAYLOAD = 230;
export const ERROR_CHAT_SET_ACTION_INTERNAL_SERVER_ERROR = 231;
export const ERROR_CHAT_SET_ACTION_FORBIDDEN = 232;

// Group room errors 3xx

export const ERROR_GROUP_CREATE_BAD_PAYLOAD = 300;
export const ERROR_GROUP_CREATE_INTERNAL_SERVER_ERROR = 301;
export const ERROR_GROUP_CREATE_LIMIT_REACHED = 380;

export const ERROR_GROUP_ADD_MEMBER_BAD_PAYLOAD = 302;
export const ERROR_GROUP_ADD_MEMBER_INTERNAL_SERVER_ERROR = 303;
export const ERROR_GROUP_ADD_MEMBER_EXISTS = 304;
export const ERROR_GROUP_ADD_MEMBER_FORBIDDEN = 305;
export const ERROR_GROUP_ADD_MEMBER_PARTICIPANTS_COUNT_LIMIT_EXCEEDED = 362;
export const ERROR_GROUP_ADD_MEMBER_PRIVACY_PROTECTION = 379;

export const ERROR_GROUP_SEND_MESSAGE_BAD_PAYLOAD = 306;
export const ERROR_GROUP_SEND_MESSAGE_INTERNAL_SERVER_ERROR = 307;
export const ERROR_GROUP_SEND_MESSAGE_FORBIDDEN = 308;

export const ERROR_GROUP_UPDATE_STATUS_BAD_PAYLOAD = 309;
export const ERROR_GROUP_UPDATE_STATUS_INTERNAL_SERVER_ERROR = 310;
export const ERROR_GROUP_UPDATE_STATUS_FORBIDDEN = 311;

export const ERROR_GROUP_DELETE_MESSAGE_BAD_PAYLOAD = 312;
export const ERROR_GROUP_DELETE_MESSAGE_INTERNAL_SERVER_ERROR = 313;
export const ERROR_GROUP_DELETE_MESSAGE_FORBIDDEN = 314;

export const ERROR_GROUP_CLEAR_MESSAGE_BAD_PAYLOAD = 315;
export const ERROR_GROUP_CLEAR_MESSAGE_INTERNAL_SERVER_ERROR = 316;
export const ERROR_GROUP_CLEAR_MESSAGE_FORBIDDEN = 317;

export const ERROR_GROUP_ADD_MODERATOR_BAD_PAYLOAD = 318;
export const ERROR_GROUP_ADD_MODERATOR_INTERNAL_SERVER_ERROR = 319;
export const ERROR_GROUP_ADD_MODERATOR_FORBIDDEN = 320;

export const ERROR_GROUP_ADD_ADMIN_BAD_PAYLOAD = 321;
export const ERROR_GROUP_ADD_ADMIN_INTERNAL_SERVER_ERROR = 322;
export const ERROR_GROUP_ADD_ADMIN_FORBIDDEN = 323;

export const ERROR_GROUP_KICK_MODERATOR_BAD_PAYLOAD = 324;
export const ERROR_GROUP_KICK_MODERATOR_INTERNAL_SERVER_ERROR = 325;
export const ERROR_GROUP_KICK_MODERATOR_FORBIDDEN = 326;

export const ERROR_GROUP_KICK_ADMIN_BAD_PAYLOAD = 327;
export const ERROR_GROUP_KICK_ADMIN_INTERNAL_SERVER_ERROR = 328;
export const ERROR_GROUP_KICK_ADMIN_FORBIDDEN = 329;

export const ERROR_GROUP_EDIT_BAD_PAYLOAD = 330;
export const ERROR_GROUP_EDIT_INTERNAL_SERVER_ERROR = 331;
export const ERROR_GROUP_EDIT_FORBIDDEN = 363;

export const ERROR_GROUP_KICK_MEMBER_BAD_PAYLOAD = 332;
export const ERROR_GROUP_KICK_MEMBER_INTERNAL_SERVER_ERROR = 333;
export const ERROR_GROUP_KICK_MEMBER_FORBIDDEN = 334;

export const ERROR_GROUP_LEFT_BAD_PAYLOAD = 335;
export const ERROR_GROUP_LEFT_INTERNAL_SERVER_ERROR = 336;
export const ERROR_GROUP_LEFT_FORBIDDEN = 337;

export const ERROR_GROUP_AVATAR_ADD_BAD_PAYLOAD = 338;
export const ERROR_GROUP_AVATAR_ADD_INTERNAL_SERVER_ERROR = 339;
export const ERROR_GROUP_AVATAR_ADD_FORBIDDEN = 340;

export const ERROR_GROUP_AVATAR_DELETE_BAD_PAYLOAD = 341;
export const ERROR_GROUP_AVATAR_DELETE_INTERNAL_SERVER_ERROR = 342;
export const ERROR_GROUP_AVATAR_DELETE_FORBIDDEN = 343;

export const ERROR_GROUP_AVATAR_GET_LIST_BAD_PAYLOAD = 344;
export const ERROR_GROUP_AVATAR_GET_LIST_INTERNAL_SERVER_ERROR = 345;
export const ERROR_GROUP_AVATAR_GET_LIST_FORBIDDEN = 346;

export const ERROR_GROUP_UPDATE_DRAFT_BAD_PAYLOAD = 347;
export const ERROR_GROUP_UPDATE_DRAFT_INTERNAL_SERVER_ERROR = 348;
export const ERROR_GROUP_UPDATE_DRAFT_FORBIDDEN = 349;

export const ERROR_GROUP_GET_DRAFT_BAD_PAYLOAD = 350;
export const ERROR_GROUP_GET_DRAFT_INTERNAL_SERVER_ERROR = 351;
export const ERROR_GROUP_GET_DRAFT_FORBIDDEN = 352;

export const ERROR_GROUP_GET_MEMBER_LIST_BAD_PAYLOAD = 353;
export const ERROR_GROUP_GET_MEMBER_LIST_INTERNAL_SERVER_ERROR = 354;
export const ERROR_GROUP_GET_MEMBER_LIST_FORBIDDEN = 355;

export const ERROR_GROUP_DELETE_BAD_PAYLOAD = 356;
export const ERROR_GROUP_DELETE_INTERNAL_SERVER_ERROR = 357;
export const ERROR_GROUP_DELETE_FORBIDDEN = 358;

export const ERROR_GROUP_SET_ACTION_BAD_PAYLOAD = 359;
export const ERROR_GROUP_SET_ACTION_INTERNAL_SERVER_ERROR = 360;
export const ERROR_GROUP_SET_ACTION_FORBIDDEN = 361;

export const ERROR_GROUP_CHECK_USERNAME_BAD_PAYLOAD = 364;
export const ERROR_GROUP_CHECK_USERNAME_INTERNAL_SERVER_ERROR = 365;

export const ERROR_GROUP_UPDATE_USERNAME_BAD_PAYLOAD = 366;
export const ERROR_GROUP_UPDATE_USERNAME_INTERNAL_SERVER_ERROR = 367;
export const ERROR_GROUP_UPDATE_USERNAME_UPDATE_LOCK = 368;
export const ERROR_GROUP_UPDATE_USERNAME_FORBIDDEN = 369;

export const ERROR_GROUP_REMOVE_USERNAME_BAD_PAYLOAD = 370;
export const ERROR_GROUP_REMOVE_USERNAME_INTERNAL_SERVER_ERROR = 371;
export const ERROR_GROUP_REMOVE_USERNAME_FORBIDDEN = 372;

export const ERROR_GROUP_REVOKE_LINK_BAD_PAYLOAD = 373;
export const ERROR_GROUP_REVOKE_LINK_INTERNAL_SERVER_ERROR = 374;
export const ERROR_GROUP_REVOKE_LINK_FORBIDDEN = 375;

export const ERROR_GROUP_EDIT_MESSAGE_BAD_PAYLOAD = 376;
export const ERROR_GROUP_EDIT_MESSAGE_INTERNAL_SERVER_ERROR = 377;
export const ERROR_GROUP_EDIT_MESSAGE_FORBIDDEN = 378;

export const ERROR_GROUP_PIN_MESSAGE_BAD_PAYLOAD = 381;
export const ERROR_GROUP_PIN_MESSAGE_INTERNAL_SERVER_ERROR = 382;
export const ERROR_GROUP_PIN_MESSAGE_FORBIDDEN = 383;

// Channel room errors 4xx

export const ERROR_CHANNEL_CREATE_BAD_PAYLOAD = 400;
export const ERROR_CHANNEL_CREATE_INTERNAL_SERVER_ERROR = 401;
export const ERROR_CHANNEL_CREATE_LIMIT_REACHED = 479;

export const ERROR_CHANNEL_ADD_MEMBER_BAD_PAYLOAD = 402;
export const ERROR_CHANNEL_ADD_MEMBER_INTERNAL_SERVER_ERROR = 403;
export const ERROR_CHANNEL_ADD_MEMBER_EXISTS = 404;
export const ERROR_CHANNEL_ADD_MEMBER_FORBIDDEN = 405;
export const ERROR_CHANNEL_ADD_MEMBER_PRIVACY_PROTECTION = 478;

export const ERROR_CHANNEL_SEND_MESSAGE_BAD_PAYLOAD = 406;
export const ERROR_CHANNEL_SEND_MESSAGE_INTERNAL_SERVER_ERROR = 407;
export const ERROR_CHANNEL_SEND_MESSAGE_FORBIDDEN = 408;

export const ERROR_CHANNEL_DELETE_BAD_PAYLOAD = 409;
export const ERROR_CHANNEL_DELETE_INTERNAL_SERVER_ERROR = 410;
export const ERROR_CHANNEL_DELETE_FORBIDDEN = 411;

export const ERROR_CHANNEL_DELETE_MESSAGE_BAD_PAYLOAD = 412;
export const ERROR_CHANNEL_DELETE_MESSAGE_INTERNAL_SERVER_ERROR = 413;
export const ERROR_CHANNEL_DELETE_MESSAGE_FORBIDDEN = 414;

export const ERROR_CHANNEL_GET_MEMBER_LIST_BAD_PAYLOAD = 415;
export const ERROR_CHANNEL_GET_MEMBER_LIST_INTERNAL_SERVER_ERROR = 416;
export const ERROR_CHANNEL_GET_MEMBER_LIST_FORBIDDEN = 417;

export const ERROR_CHANNEL_ADD_MODERATOR_BAD_PAYLOAD = 418;
export const ERROR_CHANNEL_ADD_MODERATOR_INTERNAL_SERVER_ERROR = 419;
export const ERROR_CHANNEL_ADD_MODERATOR_FORBIDDEN = 420;

export const ERROR_CHANNEL_ADD_ADMIN_BAD_PAYLOAD = 421;
export const ERROR_CHANNEL_ADD_ADMIN_INTERNAL_SERVER_ERROR = 422;
export const ERROR_CHANNEL_ADD_ADMIN_FORBIDDEN = 423;

export const ERROR_CHANNEL_KICK_MODERATOR_BAD_PAYLOAD = 424;
export const ERROR_CHANNEL_KICK_MODERATOR_INTERNAL_SERVER_ERROR = 425;
export const ERROR_CHANNEL_KICK_MODERATOR_FORBIDDEN = 426;

export const ERROR_CHANNEL_KICK_ADMIN_BAD_PAYLOAD = 427;
export const ERROR_CHANNEL_KICK_ADMIN_INTERNAL_SERVER_ERROR = 428;
export const ERROR_CHANNEL_KICK_ADMIN_FORBIDDEN = 429;

export const ERROR_CHANNEL_EDIT_BAD_PAYLOAD = 430;
export const ERROR_CHANNEL_EDIT_INTERNAL_SERVER_ERROR = 431;
export const ERROR_CHANNEL_EDIT_FORBIDDEN = 459;

export const ERROR_CHANNEL_KICK_MEMBER_BAD_PAYLOAD = 432;
export const ERROR_CHANNEL_KICK_MEMBER_INTERNAL_SERVER_ERROR = 433;
export const ERROR_CHANNEL_KICK_MEMBER_FORBIDDEN = 434;

export const ERROR_CHANNEL_LEFT_BAD_PAYLOAD = 435;
export const ERROR_CHANNEL_LEFT_INTERNAL_SERVER_ERROR = 436;
export const ERROR_CHANNEL_LEFT_FORBIDDEN = 437;

export const ERROR_CHANNEL_AVATAR_ADD_BAD_PAYLOAD = 438;
export const ERROR_CHANNEL_AVATAR_ADD_INTERNAL_SERVER_ERROR = 439;
export const ERROR_CHANNEL_AVATAR_ADD_FORBIDDEN = 440;

export const ERROR_CHANNEL_AVATAR_DELETE_BAD_PAYLOAD = 441;
export const ERROR_CHANNEL_AVATAR_DELETE_INTERNAL_SERVER_ERROR = 442;
export const ERROR_CHANNEL_AVATAR_DELETE_FORBIDDEN = 443;

export const ERROR_CHANNEL_AVATAR_GET_LIST_BAD_PAYLOAD = 444;
export const ERROR_CHANNEL_AVATAR_GET_LIST_INTERNAL_SERVER_ERROR = 445;
export const ERROR_CHANNEL_AVATAR_GET_LIST_FORBIDDEN = 446;

export const ERROR_CHANNEL_UPDATE_DRAFT_BAD_PAYLOAD = 447;
export const ERROR_CHANNEL_UPDATE_DRAFT_INTERNAL_SERVER_ERROR = 448;
export const ERROR_CHANNEL_UPDATE_DRAFT_FORBIDDEN = 449;

export const ERROR_CHANNEL_GET_DRAFT_BAD_PAYLOAD = 450;
export const ERROR_CHANNEL_GET_DRAFT_INTERNAL_SERVER_ERROR = 451;
export const ERROR_CHANNEL_GET_DRAFT_FORBIDDEN = 452;

export const ERROR_CHANNEL_CHECK_USERNAME_BAD_PAYLOAD = 453;
export const ERROR_CHANNEL_CHECK_USERNAME_INTERNAL_SERVER_ERROR = 454;

export const ERROR_CHANNEL_UPDATE_USERNAME_BAD_PAYLOAD = 455;
export const ERROR_CHANNEL_UPDATE_USERNAME_INTERNAL_SERVER_ERROR = 456;
export const ERROR_CHANNEL_UPDATE_USERNAME_UPDATE_LOCK = 457;
export const ERROR_CHANNEL_UPDATE_USERNAME_FORBIDDEN = 458;

export const ERROR_CHANNEL_REMOVE_USERNAME_BAD_PAYLOAD = 460;
export const ERROR_CHANNEL_REMOVE_USERNAME_INTERNAL_SERVER_ERROR = 461;
export const ERROR_CHANNEL_REMOVE_USERNAME_FORBIDDEN = 462;

export const ERROR_CHANNEL_REVOKE_LINK_BAD_PAYLOAD = 463;
export const ERROR_CHANNEL_REVOKE_LINK_INTERNAL_SERVER_ERROR = 464;
export const ERROR_CHANNEL_REVOKE_LINK_FORBIDDEN = 465;

export const ERROR_CHANNEL_UPDATE_SIGNATURE_BAD_PAYLOAD = 466;
export const ERROR_CHANNEL_UPDATE_SIGNATURE_INTERNAL_SERVER_ERROR = 467;
export const ERROR_CHANNEL_UPDATE_SIGNATURE_FORBIDDEN = 468;

export const ERROR_CHANNEL_GET_MESSAGES_STATS_BAD_PAYLOAD = 469;
export const ERROR_CHANNEL_GET_MESSAGES_STATS_INTERNAL_SERVER_ERROR = 470;
export const ERROR_CHANNEL_GET_MESSAGES_STATS_FORBIDDEN = 471;

export const ERROR_CHANNEL_ADD_MESSAGE_REACTION_BAD_PAYLOAD = 472;
export const ERROR_CHANNEL_ADD_MESSAGE_REACTION_INTERNAL_SERVER_ERROR = 473;
export const ERROR_CHANNEL_ADD_MESSAGE_REACTION_FORBIDDEN = 474;

export const ERROR_CHANNEL_EDIT_MESSAGE_BAD_PAYLOAD = 475;
export const ERROR_CHANNEL_EDIT_MESSAGE_INTERNAL_SERVER_ERROR = 476;
export const ERROR_CHANNEL_EDIT_MESSAGE_FORBIDDEN = 477;

export const ERROR_CHANNEL_UPDATE_REACTION_STATUS_BAD_PAYLOAD = 480;
export const ERROR_CHANNEL_UPDATE_REACTION_STATUS_INTERNAL_SERVER_ERROR = 481;
export const ERROR_CHANNEL_UPDATE_REACTION_STATUS_FORBIDDEN = 482;

export const ERROR_CHANNEL_PIN_MESSAGE_BAD_PAYLOAD = 483;
export const ERROR_CHANNEL_PIN_MESSAGE_INTERNAL_SERVER_ERROR = 484;
export const ERROR_CHANNEL_PIN_MESSAGE_FORBIDDEN = 485;

// Info errors 5xx

export const ERROR_INFO_LOCATION_NOT_FOUND = 500;

export const ERROR_INFO_COUNTRY_BAD_PAYLOAD = 501;

export const ERROR_INFO_PAGE_BAD_PAYLOAD = 502;
export const ERROR_INFO_PAGE_INTERNAL_SERVER_ERROR = 503;

export const ERROR_INFO_WALLPAPER_BAD_PAYLOAD = 504;
export const ERROR_INFO_WALLPAPER_INTERNAL_SERVER_ERROR = 505;

// Client errors 6xx

export const ERROR_CLIENT_CONDITION_BAD_PAYLOAD = 600;
export const ERROR_CLIENT_CONDITION_INTERNAL_SERVER_ERROR = 601;

export const ERROR_CLIENT_UPDATE_MESSAGE_BAD_PAYLOAD = 602;
export const ERROR_CLIENT_UPDATE_MESSAGE_INTERNAL_SERVER_ERROR = 603;
export const ERROR_CLIENT_UPDATE_MESSAGE_FORBIDDEN = 604;

export const ERROR_CLIENT_UPDATE_DELETE_MESSAGE_BAD_PAYLOAD = 605;
export const ERROR_CLIENT_UPDATE_DELETE_MESSAGE_INTERNAL_SERVER_ERROR = 606;

export const ERROR_CLIENT_UPDATE_MESSAGE_STATUS_BAD_PAYLOAD = 607;
export const ERROR_CLIENT_UPDATE_MESSAGE_STATUS_INTERNAL_SERVER_ERROR = 608;
export const ERROR_CLIENT_UPDATE_MESSAGE_STATUS_FORBIDDEN = 609;

export const ERROR_CLIENT_GET_ROOM_LIST_BAD_PAYLOAD = 610;
export const ERROR_CLIENT_GET_ROOM_LIST_INTERNAL_SERVER_ERROR = 611;

export const ERROR_CLIENT_GET_ROOM_BAD_PAYLOAD = 612;
export const ERROR_CLIENT_GET_ROOM_INTERNAL_SERVER_ERROR = 613;
export const ERROR_CLIENT_GET_ROOM_NOT_FOUND = 614;

export const ERROR_CLIENT_GET_ROOM_HISTORY_BAD_PAYLOAD = 615;
export const ERROR_CLIENT_GET_ROOM_HISTORY_INTERNAL_SERVER_ERROR = 616;
export const ERROR_CLIENT_GET_ROOM_HISTORY_NOT_FOUND = 617;

export const ERROR_CLIENT_SEARCH_ROOM_HISTORY_BAD_PAYLOAD = 618;
export const ERROR_CLIENT_SEARCH_ROOM_HISTORY_INTERNAL_SERVER_ERROR = 619;
export const ERROR_CLIENT_SEARCH_ROOM_HISTORY_NOT_FOUND = 620;

export const ERROR_CLIENT_RESOLVE_USERNAME_BAD_PAYLOAD = 621;
export const ERROR_CLIENT_RESOLVE_USERNAME_INTERNAL_SERVER_ERROR = 622;
export const ERROR_CLIENT_RESOLVE_USERNAME_NOT_FOUND = 623;

export const ERROR_CLIENT_GET_ROOM_MESSAGE_BAD_PAYLOAD = 624;
export const ERROR_CLIENT_GET_ROOM_MESSAGE_INTERNAL_SERVER_ERROR = 625;
export const ERROR_CLIENT_GET_ROOM_MESSAGE_NOT_FOUND = 626;

export const ERROR_CLIENT_CHECK_INVITE_LINK_BAD_PAYLOAD = 627;
export const ERROR_CLIENT_CHECK_INVITE_LINK_INTERNAL_SERVER_ERROR = 628;
export const ERROR_CLIENT_CHECK_INVITE_LINK_NOT_FOUND = 629;

export const ERROR_CLIENT_JOIN_BY_INVITE_LINK_BAD_PAYLOAD = 630;
export const ERROR_CLIENT_JOIN_BY_INVITE_LINK_INTERNAL_SERVER_ERROR = 631;
export const ERROR_CLIENT_JOIN_BY_INVITE_LINK_FORBIDDEN = 632;
export const ERROR_CLIENT_JOIN_BY_INVITE_LINK_ALREADY_JOINED = 633;
export const ERROR_CLIENT_JOIN_BY_INVITE_LINK_PARTICIPANTS_COUNT_LIMIT_EXCEEDED = 634;

export const ERROR_CLIENT_JOIN_BY_USERNAME_BAD_PAYLOAD = 635;
export const ERROR_CLIENT_JOIN_BY_USERNAME_INTERNAL_SERVER_ERROR = 636;
export const ERROR_CLIENT_JOIN_BY_USERNAME_FORBIDDEN = 637;
export const ERROR_CLIENT_JOIN_BY_USERNAME_ALREADY_JOINED = 638;
export const ERROR_CLIENT_JOIN_BY_USERNAME_PARTICIPANTS_COUNT_LIMIT_EXCEEDED = 639;

export const ERROR_CLIENT_SUBSCRIBE_TO_ROOM_BAD_PAYLOAD = 640;
export const ERROR_CLIENT_SUBSCRIBE_TO_ROOM_INTERNAL_SERVER_ERROR = 641;
export const ERROR_CLIENT_SUBSCRIBE_TO_ROOM_FORBIDDEN = 642;

export const ERROR_CLIENT_UNSUBSCRIBE_FROM_ROOM_BAD_PAYLOAD = 643;
export const ERROR_CLIENT_UNSUBSCRIBE_FROM_ROOM_INTERNAL_SERVER_ERROR = 644;

export const ERROR_CLIENT_SEARCH_USERNAME_BAD_PAYLOAD = 645;
export const ERROR_CLIENT_SEARCH_USERNAME_INTERNAL_SERVER_ERROR = 646;

export const ERROR_CLIENT_COUNT_ROOM_HISTORY_BAD_PAYLOAD = 647;
export const ERROR_CLIENT_COUNT_ROOM_HISTORY_INTERNAL_SERVER_ERROR = 648;
export const ERROR_CLIENT_COUNT_ROOM_HISTORY_NOT_FOUND = 649;

export const ERROR_CLIENT_MUTE_ROOM_BAD_PAYLOAD = 650;
export const ERROR_CLIENT_MUTE_ROOM_INTERNAL_SERVER_ERROR = 651;
export const ERROR_CLIENT_MUTE_ROOM_FORBIDDEN = 652;

export const ERROR_CLIENT_PIN_ROOM_BAD_PAYLOAD = 653;
export const ERROR_CLIENT_PIN_ROOM_INTERNAL_SERVER_ERROR = 654;
export const ERROR_CLIENT_PIN_ROOM_FORBIDDEN = 655;

export const ERROR_CLIENT_ROOM_REPORT_BAD_PAYLOAD = 656;
export const ERROR_CLIENT_ROOM_REPORT_INTERNAL_SERVER_ERROR = 657;
export const ERROR_CLIENT_ROOM_REPORT_REPORTED_BEFORE = 658;
export const ERROR_CLIENT_ROOM_REPORT_FORBIDDEN = 659;
export const ERROR_CLIENT_REGISTER_DEVICE_BAD_PAYLOAD = 660;
export const ERROR_CLIENT_REGISTER_DEVICE_INTERNAL_SERVER_ERROR = 661;
export const ERROR_CLIENT_REGISTER_DEVICE_FORBIDDEN = 662;

// File errors 7xx

export const ERROR_FILE_UPLOAD_OPTION_BAD_PAYLOAD = 700;
export const ERROR_FILE_UPLOAD_OPTION_INTERNAL_SERVER_ERROR = 701;

export const ERROR_FILE_UPLOAD_INIT_BAD_PAYLOAD = 702;
export const ERROR_FILE_UPLOAD_INIT_INTERNAL_SERVER_ERROR = 703;

export const ERROR_FILE_UPLOAD_BAD_PAYLOAD = 704;
export const ERROR_FILE_UPLOAD_INTERNAL_SERVER_ERROR = 705;
export const ERROR_FILE_UPLOAD_FORBIDDEN = 706;

export const ERROR_FILE_UPLOAD_STATUS_BAD_PAYLOAD = 707;
export const ERROR_FILE_UPLOAD_STATUS_INTERNAL_SERVER_ERROR = 708;
export const ERROR_FILE_UPLOAD_STATUS_NOT_FOUND = 709;

export const ERROR_FILE_INFO_BAD_PAYLOAD = 710;
export const ERROR_FILE_INFO_INTERNAL_SERVER_ERROR = 711;
export const ERROR_FILE_INFO_NOT_FOUND = 712;

export const ERROR_FILE_DOWNLOAD_BAD_PAYLOAD = 713;
export const ERROR_FILE_DOWNLOAD_INTERNAL_SERVER_ERROR = 714;
export const ERROR_FILE_DOWNLOAD_NOT_FOUND = 715;

// QR code errors 7xx

export const ERROR_QR_CODE_JOIN_BAD_PAYLOAD = 800;
export const ERROR_QR_CODE_JOIN_INTERNAL_SERVER_ERROR = 801;

export const ERROR_QR_CODE_RESOLVE_BAD_PAYLOAD = 802;
export const ERROR_QR_CODE_RESOLVE_INTERNAL_SERVER_ERROR = 803;

export const ERROR_QR_CODE_NEW_DEVICE_BAD_PAYLOAD = 804;
export const ERROR_QR_CODE_NEW_DEVICE_INTERNAL_SERVER_ERROR = 805;

export const ERROR_QR_CODE_ADD_CONTACT_BAD_PAYLOAD = 806;
export const ERROR_QR_CODE_ADD_CONTACT_INTERNAL_SERVER_ERROR = 807;

export const ERROR_QR_CODE_ADD_ME_BAD_PAYLOAD = 808;
export const ERROR_QR_CODE_ADD_ME_INTERNAL_SERVER_ERROR = 809;

// Signaling errors 9xx

export const ERROR_SIGNALING_GET_CONFIGURATION_BAD_PAYLOAD = 900;
export const ERROR_SIGNALING_GET_CONFIGURATION_INTERNAL_SERVER_ERROR = 901;

export const ERROR_SIGNALING_OFFER_BAD_PAYLOAD = 902;
export const ERROR_SIGNALING_OFFER_INTERNAL_SERVER_ERROR = 903;
export const ERROR_SIGNALING_OFFER_FORBIDDEN = 904;
export const ERROR_SIGNALING_OFFER_BLOCKED_BY_PEER = 905;
export const ERROR_SIGNALING_OFFER_PRIVACY_PROTECTION = 906;

export const ERROR_SIGNALING_RINGING_BAD_PAYLOAD = 907;
export const ERROR_SIGNALING_RINGING_INTERNAL_SERVER_ERROR = 908;
export const ERROR_SIGNALING_RINGING_FORBIDDEN = 909;

export const ERROR_SIGNALING_ACCEPT_BAD_PAYLOAD = 910;
export const ERROR_SIGNALING_ACCEPT_INTERNAL_SERVER_ERROR = 911;
export const ERROR_SIGNALING_ACCEPT_FORBIDDEN = 912;

export const ERROR_SIGNALING_CANDIDATE_BAD_PAYLOAD = 913;
export const ERROR_SIGNALING_CANDIDATE_INTERNAL_SERVER_ERROR = 914;
export const ERROR_SIGNALING_CANDIDATE_FORBIDDEN = 915;

export const ERROR_SIGNALING_LEAVE_BAD_PAYLOAD = 916;
export const ERROR_SIGNALING_LEAVE_INTERNAL_SERVER_ERROR = 917;
export const ERROR_SIGNALING_LEAVE_FORBIDDEN = 918;

export const ERROR_SIGNALING_SESSION_HOLD_BAD_PAYLOAD = 919;
export const ERROR_SIGNALING_SESSION_HOLD_INTERNAL_SERVER_ERROR = 920;
export const ERROR_SIGNALING_SESSION_HOLD_FORBIDDEN = 921;

export const ERROR_SIGNALING_GET_LOG_BAD_PAYLOAD = 922;
export const ERROR_SIGNALING_GET_LOG_INTERNAL_SERVER_ERROR = 923;

export const ERROR_SIGNALING_CLEAR_LOG_BAD_PAYLOAD = 924;
export const ERROR_SIGNALING_CLEAR_LOG_INTERNAL_SERVER_ERROR = 925;

export const ERROR_SIGNALING_RATE_BAD_PAYLOAD = 926;
export const ERROR_SIGNALING_RATE_INTERNAL_SERVER_ERROR = 927;
export const ERROR_SIGNALING_RATE_FORBIDDEN = 928;

// Geo errors 10xx

export const ERROR_GEO_GET_REGISTER_STATUS_BAD_PAYLOAD = 1000;
export const ERROR_GEO_GET_REGISTER_STATUS_INTERNAL_SERVER_ERROR = 1001;

export const ERROR_GEO_REGISTER_BAD_PAYLOAD = 1002;
export const ERROR_GEO_REGISTER_INTERNAL_SERVER_ERROR = 1003;

export const ERROR_GEO_UPDATE_POSITION_BAD_PAYLOAD = 1004;
export const ERROR_GEO_UPDATE_POSITION_INTERNAL_SERVER_ERROR = 1005;
export const ERROR_GEO_UPDATE_POSITION_FORBIDDEN = 1006;

export const ERROR_GEO_GET_COMMENT_BAD_PAYLOAD = 1007;
export const ERROR_GEO_GET_COMMENT_INTERNAL_SERVER_ERROR = 1008;
export const ERROR_GEO_GET_COMMENT_FORBIDDEN = 1009;

export const ERROR_GEO_UPDATE_COMMENT_BAD_PAYLOAD = 1010;
export const ERROR_GEO_UPDATE_COMMENT_INTERNAL_SERVER_ERROR = 1011;
export const ERROR_GEO_UPDATE_COMMENT_FORBIDDEN = 1012;

export const ERROR_GEO_GET_NEARBY_DISTANCE_BAD_PAYLOAD = 1013;
export const ERROR_GEO_GET_NEARBY_DISTANCE_INTERNAL_SERVER_ERROR = 1014;
export const ERROR_GEO_GET_NEARBY_DISTANCE_FORBIDDEN = 1015;

export const ERROR_GEO_GET_NEARBY_COORDINATE_BAD_PAYLOAD = 1016;
export const ERROR_GEO_GET_NEARBY_COORDINATE_INTERNAL_SERVER_ERROR = 1017;
export const ERROR_GEO_GET_NEARBY_COORDINATE_FORBIDDEN = 1018;

export const ERROR_GEO_GET_CONFIGURATION_BAD_PAYLOAD = 1019;
export const ERROR_GEO_GET_CONFIGURATION_INTERNAL_SERVER_ERROR = 1020;