export default {
  countryAB: {id: 'country.AB', defaultMessage: 'Abkhazia', description: 'Abkhazia country name'},
  countryAF: {id: 'country.AF', defaultMessage: 'Afghanistan', description: 'Afghanistan country name'},
  countryAX: {id: 'country.AX', defaultMessage: 'Åland Islands', description: 'Åland Islands country name'},
  countryAL: {id: 'country.AL', defaultMessage: 'Albania', description: 'Albania country name'},
  countryDZ: {id: 'country.DZ', defaultMessage: 'Algeria', description: 'Algeria country name'},
  countryAS: {id: 'country.AS', defaultMessage: 'American Samoa', description: 'American Samoa country name'},
  countryAD: {id: 'country.AD', defaultMessage: 'Andorra', description: 'Andorra country name'},
  countryAO: {id: 'country.AO', defaultMessage: 'Angola', description: 'Angola country name'},
  countryAI: {id: 'country.AI', defaultMessage: 'Anguilla', description: 'Anguilla country name'},
  countryAG: {id: 'country.AG', defaultMessage: 'Antigua & Barbuda', description: 'Antigua & Barbuda country name'},
  countryAR: {id: 'country.AR', defaultMessage: 'Argentina', description: 'Argentina country name'},
  countryAM: {id: 'country.AM', defaultMessage: 'Armenia', description: 'Armenia country name'},
  countryAW: {id: 'country.AW', defaultMessage: 'Aruba', description: 'Aruba country name'},
  countrySH_AC: {id: 'country.SH_AC', defaultMessage: 'Ascension', description: 'Ascension country name'},
  countryAU: {id: 'country.AU', defaultMessage: 'Australia', description: 'Australia country name'},
  countryAU_ET: {
    id: 'country.AU_ET',
    defaultMessage: 'Australian External Territories',
    description: 'Australian External Territories country name',
  },
  countryAT: {id: 'country.AT', defaultMessage: 'Austria', description: 'Austria country name'},
  countryAZ: {id: 'country.AZ', defaultMessage: 'Azerbaijan', description: 'Azerbaijan country name'},
  countryBS: {id: 'country.BS', defaultMessage: 'Bahamas', description: 'Bahamas country name'},
  countryBH: {id: 'country.BH', defaultMessage: 'Bahrain', description: 'Bahrain country name'},
  countryBD: {id: 'country.BD', defaultMessage: 'Bangladesh', description: 'Bangladesh country name'},
  countryBB: {id: 'country.BB', defaultMessage: 'Barbados', description: 'Barbados country name'},
  countryAG_BAR: {id: 'country.AG_BAR', defaultMessage: 'Barbuda', description: 'Barbuda country name'},
  countryBY: {id: 'country.BY', defaultMessage: 'Belarus', description: 'Belarus country name'},
  countryBE: {id: 'country.BE', defaultMessage: 'Belgium', description: 'Belgium country name'},
  countryBZ: {id: 'country.BZ', defaultMessage: 'Belize', description: 'Belize country name'},
  countryBJ: {id: 'country.BJ', defaultMessage: 'Benin', description: 'Benin country name'},
  countryBM: {id: 'country.BM', defaultMessage: 'Bermuda', description: 'Bermuda country name'},
  countryBT: {id: 'country.BT', defaultMessage: 'Bhutan', description: 'Bhutan country name'},
  countryBO: {id: 'country.BO', defaultMessage: 'Bolivia', description: 'Bolivia country name'},
  countryBQ: {
    id: 'country.BQ',
    defaultMessage: 'Caribbean Netherlands',
    description: 'Caribbean Netherlands country name',
  },
  countryBA: {
    id: 'country.BA',
    defaultMessage: 'Bosnia & Herzegovina',
    description: 'Bosnia & Herzegovina country name',
  },
  countryBW: {id: 'country.BW', defaultMessage: 'Botswana', description: 'Botswana country name'},
  countryBR: {id: 'country.BR', defaultMessage: 'Brazil', description: 'Brazil country name'},
  countryIO: {
    id: 'country.IO',
    defaultMessage: 'British Indian Ocean Territory',
    description: 'British Indian Ocean Territory country name',
  },
  countryVG: {
    id: 'country.VG',
    defaultMessage: 'British Virgin Islands',
    description: 'British Virgin Islands country name',
  },
  countryBN: {id: 'country.BN', defaultMessage: 'Brunei', description: 'Brunei country name'},
  countryBG: {id: 'country.BG', defaultMessage: 'Bulgaria', description: 'Bulgaria country name'},
  countryBF: {id: 'country.BF', defaultMessage: 'Burkina Faso', description: 'Burkina Faso country name'},
  countryMM: {id: 'country.MM', defaultMessage: 'Myanmar (Burma)', description: 'Myanmar (Burma) country name'},
  countryBI: {id: 'country.BI', defaultMessage: 'Burundi', description: 'Burundi country name'},
  countryKH: {id: 'country.KH', defaultMessage: 'Cambodia', description: 'Cambodia country name'},
  countryCM: {id: 'country.CM', defaultMessage: 'Cameroon', description: 'Cameroon country name'},
  countryCA: {id: 'country.CA', defaultMessage: 'Canada', description: 'Canada country name'},
  countryCV: {id: 'country.CV', defaultMessage: 'Cape Verde', description: 'Cape Verde country name'},
  countryKY: {id: 'country.KY', defaultMessage: 'Cayman Islands', description: 'Cayman Islands country name'},
  countryCF: {
    id: 'country.CF',
    defaultMessage: 'Central African Republic',
    description: 'Central African Republic country name',
  },
  countryTD: {id: 'country.TD', defaultMessage: 'Chad', description: 'Chad country name'},
  countryCL: {id: 'country.CL', defaultMessage: 'Chile', description: 'Chile country name'},
  countryCN: {id: 'country.CN', defaultMessage: 'China', description: 'China country name'},
  countryCX: {id: 'country.CX', defaultMessage: 'Christmas Island', description: 'Christmas Island country name'},
  countryCC: {
    id: 'country.CC',
    defaultMessage: 'Cocos (Keeling) Islands',
    description: 'Cocos (Keeling) Islands country name',
  },
  countryCO: {id: 'country.CO', defaultMessage: 'Colombia', description: 'Colombia country name'},
  countryKM: {id: 'country.KM', defaultMessage: 'Comoros', description: 'Comoros country name'},
  countryCG: {id: 'country.CG', defaultMessage: 'Congo - Brazzaville', description: 'Congo - Brazzaville country name'},
  countryCD: {id: 'country.CD', defaultMessage: 'Congo - Kinshasa', description: 'Congo - Kinshasa country name'},
  countryCK: {id: 'country.CK', defaultMessage: 'Cook Islands', description: 'Cook Islands country name'},
  countryCR: {id: 'country.CR', defaultMessage: 'Costa Rica', description: 'Costa Rica country name'},
  countryCI: {id: 'country.CI', defaultMessage: 'Côte d’Ivoire', description: 'Côte d’Ivoire country name'},
  countryHR: {id: 'country.HR', defaultMessage: 'Croatia', description: 'Croatia country name'},
  countryCU: {id: 'country.CU', defaultMessage: 'Cuba', description: 'Cuba country name'},
  countryCW: {id: 'country.CW', defaultMessage: 'Curaçao', description: 'Curaçao country name'},
  countryCY: {id: 'country.CY', defaultMessage: 'Cyprus', description: 'Cyprus country name'},
  countryCZ: {id: 'country.CZ', defaultMessage: 'Czech Republic', description: 'Czech Republic country name'},
  countryDK: {id: 'country.DK', defaultMessage: 'Denmark', description: 'Denmark country name'},
  countryDG: {id: 'country.DG', defaultMessage: 'Diego Garcia', description: 'Diego Garcia country name'},
  countryDJ: {id: 'country.DJ', defaultMessage: 'Djibouti', description: 'Djibouti country name'},
  countryDM: {id: 'country.DM', defaultMessage: 'Dominica', description: 'Dominica country name'},
  countryDO: {id: 'country.DO', defaultMessage: 'Dominican Republic', description: 'Dominican Republic country name'},
  countryTL: {id: 'country.TL', defaultMessage: 'Timor-Leste', description: 'Timor-Leste country name'},
  countryEC: {id: 'country.EC', defaultMessage: 'Ecuador', description: 'Ecuador country name'},
  countryEG: {id: 'country.EG', defaultMessage: 'Egypt', description: 'Egypt country name'},
  countrySV: {id: 'country.SV', defaultMessage: 'El Salvador', description: 'El Salvador country name'},
  countryGQ: {id: 'country.GQ', defaultMessage: 'Equatorial Guinea', description: 'Equatorial Guinea country name'},
  countryER: {id: 'country.ER', defaultMessage: 'Eritrea', description: 'Eritrea country name'},
  countryEE: {id: 'country.EE', defaultMessage: 'Estonia', description: 'Estonia country name'},
  countryET: {id: 'country.ET', defaultMessage: 'Ethiopia', description: 'Ethiopia country name'},
  countryFK: {id: 'country.FK', defaultMessage: 'Falkland Islands', description: 'Falkland Islands country name'},
  countryFO: {id: 'country.FO', defaultMessage: 'Faroe Islands', description: 'Faroe Islands country name'},
  countryFJ: {id: 'country.FJ', defaultMessage: 'Fiji', description: 'Fiji country name'},
  countryFI: {id: 'country.FI', defaultMessage: 'Finland', description: 'Finland country name'},
  countryFR: {id: 'country.FR', defaultMessage: 'France', description: 'France country name'},
  countryGF: {id: 'country.GF', defaultMessage: 'French Guiana', description: 'French Guiana country name'},
  countryPF: {id: 'country.PF', defaultMessage: 'French Polynesia', description: 'French Polynesia country name'},
  countryGA: {id: 'country.GA', defaultMessage: 'Gabon', description: 'Gabon country name'},
  countryGM: {id: 'country.GM', defaultMessage: 'Gambia', description: 'Gambia country name'},
  countryGE: {id: 'country.GE', defaultMessage: 'Georgia', description: 'Georgia country name'},
  countryDE: {id: 'country.DE', defaultMessage: 'Germany', description: 'Germany country name'},
  countryGH: {id: 'country.GH', defaultMessage: 'Ghana', description: 'Ghana country name'},
  countryGI: {id: 'country.GI', defaultMessage: 'Gibraltar', description: 'Gibraltar country name'},
  countryGR: {id: 'country.GR', defaultMessage: 'Greece', description: 'Greece country name'},
  countryGL: {id: 'country.GL', defaultMessage: 'Greenland', description: 'Greenland country name'},
  countryGD: {id: 'country.GD', defaultMessage: 'Grenada', description: 'Grenada country name'},
  countryGP: {id: 'country.GP', defaultMessage: 'Guadeloupe', description: 'Guadeloupe country name'},
  countryGU: {id: 'country.GU', defaultMessage: 'Guam', description: 'Guam country name'},
  countryGT: {id: 'country.GT', defaultMessage: 'Guatemala', description: 'Guatemala country name'},
  countryGG: {id: 'country.GG', defaultMessage: 'Guernsey', description: 'Guernsey country name'},
  countryGN: {id: 'country.GN', defaultMessage: 'Guinea', description: 'Guinea country name'},
  countryGW: {id: 'country.GW', defaultMessage: 'Guinea-Bissau', description: 'Guinea-Bissau country name'},
  countryGY: {id: 'country.GY', defaultMessage: 'Guyana', description: 'Guyana country name'},
  countryHT: {id: 'country.HT', defaultMessage: 'Haiti', description: 'Haiti country name'},
  countryHN: {id: 'country.HN', defaultMessage: 'Honduras', description: 'Honduras country name'},
  countryHK: {id: 'country.HK', defaultMessage: 'Hong Kong SAR China', description: 'Hong Kong SAR China country name'},
  countryHU: {id: 'country.HU', defaultMessage: 'Hungary', description: 'Hungary country name'},
  countryIS: {id: 'country.IS', defaultMessage: 'Iceland', description: 'Iceland country name'},
  countryIN: {id: 'country.IN', defaultMessage: 'India', description: 'India country name'},
  countryID: {id: 'country.ID', defaultMessage: 'Indonesia', description: 'Indonesia country name'},
  countryIR: {id: 'country.IR', defaultMessage: 'Iran', description: 'Iran country name'},
  countryIQ: {id: 'country.IQ', defaultMessage: 'Iraq', description: 'Iraq country name'},
  countryIE: {id: 'country.IE', defaultMessage: 'Ireland', description: 'Ireland country name'},
  countryIT: {id: 'country.IT', defaultMessage: 'Italy', description: 'Italy country name'},
  countryJM: {id: 'country.JM', defaultMessage: 'Jamaica', description: 'Jamaica country name'},
  countrySJ: {
    id: 'country.SJ',
    defaultMessage: 'Svalbard & Jan Mayen',
    description: 'Svalbard & Jan Mayen country name',
  },
  countryJP: {id: 'country.JP', defaultMessage: 'Japan', description: 'Japan country name'},
  countryJE: {id: 'country.JE', defaultMessage: 'Jersey', description: 'Jersey country name'},
  countryJO: {id: 'country.JO', defaultMessage: 'Jordan', description: 'Jordan country name'},
  countryKZ: {id: 'country.KZ', defaultMessage: 'Kazakhstan', description: 'Kazakhstan country name'},
  countryKE: {id: 'country.KE', defaultMessage: 'Kenya', description: 'Kenya country name'},
  countryKI: {id: 'country.KI', defaultMessage: 'Kiribati', description: 'Kiribati country name'},
  countryKP: {id: 'country.KP', defaultMessage: 'North Korea', description: 'North Korea country name'},
  countryKR: {id: 'country.KR', defaultMessage: 'South Korea', description: 'South Korea country name'},
  countryKW: {id: 'country.KW', defaultMessage: 'Kuwait', description: 'Kuwait country name'},
  countryKG: {id: 'country.KG', defaultMessage: 'Kyrgyzstan', description: 'Kyrgyzstan country name'},
  countryLA: {id: 'country.LA', defaultMessage: 'Laos', description: 'Laos country name'},
  countryLV: {id: 'country.LV', defaultMessage: 'Latvia', description: 'Latvia country name'},
  countryLB: {id: 'country.LB', defaultMessage: 'Lebanon', description: 'Lebanon country name'},
  countryLS: {id: 'country.LS', defaultMessage: 'Lesotho', description: 'Lesotho country name'},
  countryLR: {id: 'country.LR', defaultMessage: 'Liberia', description: 'Liberia country name'},
  countryLY: {id: 'country.LY', defaultMessage: 'Libya', description: 'Libya country name'},
  countryLI: {id: 'country.LI', defaultMessage: 'Liechtenstein', description: 'Liechtenstein country name'},
  countryLT: {id: 'country.LT', defaultMessage: 'Lithuania', description: 'Lithuania country name'},
  countryLU: {id: 'country.LU', defaultMessage: 'Luxembourg', description: 'Luxembourg country name'},
  countryMO: {id: 'country.MO', defaultMessage: 'Macau SAR China', description: 'Macau SAR China country name'},
  countryMK: {id: 'country.MK', defaultMessage: 'Macedonia', description: 'Macedonia country name'},
  countryMG: {id: 'country.MG', defaultMessage: 'Madagascar', description: 'Madagascar country name'},
  countryMW: {id: 'country.MW', defaultMessage: 'Malawi', description: 'Malawi country name'},
  countryMY: {id: 'country.MY', defaultMessage: 'Malaysia', description: 'Malaysia country name'},
  countryMV: {id: 'country.MV', defaultMessage: 'Maldives', description: 'Maldives country name'},
  countryML: {id: 'country.ML', defaultMessage: 'Mali', description: 'Mali country name'},
  countryMT: {id: 'country.MT', defaultMessage: 'Malta', description: 'Malta country name'},
  countryMH: {id: 'country.MH', defaultMessage: 'Marshall Islands', description: 'Marshall Islands country name'},
  countryMQ: {id: 'country.MQ', defaultMessage: 'Martinique', description: 'Martinique country name'},
  countryMR: {id: 'country.MR', defaultMessage: 'Mauritania', description: 'Mauritania country name'},
  countryMU: {id: 'country.MU', defaultMessage: 'Mauritius', description: 'Mauritius country name'},
  countryYT: {id: 'country.YT', defaultMessage: 'Mayotte', description: 'Mayotte country name'},
  countryMX: {id: 'country.MX', defaultMessage: 'Mexico', description: 'Mexico country name'},
  countryFM: {id: 'country.FM', defaultMessage: 'Micronesia', description: 'Micronesia country name'},
  countryMD: {id: 'country.MD', defaultMessage: 'Moldova', description: 'Moldova country name'},
  countryMC: {id: 'country.MC', defaultMessage: 'Monaco', description: 'Monaco country name'},
  countryMN: {id: 'country.MN', defaultMessage: 'Mongolia', description: 'Mongolia country name'},
  countryME: {id: 'country.ME', defaultMessage: 'Montenegro', description: 'Montenegro country name'},
  countryMS: {id: 'country.MS', defaultMessage: 'Montserrat', description: 'Montserrat country name'},
  countryMA: {id: 'country.MA', defaultMessage: 'Morocco', description: 'Morocco country name'},
  countryMZ: {id: 'country.MZ', defaultMessage: 'Mozambique', description: 'Mozambique country name'},
  countryNA: {id: 'country.NA', defaultMessage: 'Namibia', description: 'Namibia country name'},
  countryNR: {id: 'country.NR', defaultMessage: 'Nauru', description: 'Nauru country name'},
  countryNP: {id: 'country.NP', defaultMessage: 'Nepal', description: 'Nepal country name'},
  countryNL: {id: 'country.NL', defaultMessage: 'Netherlands', description: 'Netherlands country name'},
  countryNC: {id: 'country.NC', defaultMessage: 'New Caledonia', description: 'New Caledonia country name'},
  countryNZ: {id: 'country.NZ', defaultMessage: 'New Zealand', description: 'New Zealand country name'},
  countryNI: {id: 'country.NI', defaultMessage: 'Nicaragua', description: 'Nicaragua country name'},
  countryNE: {id: 'country.NE', defaultMessage: 'Niger', description: 'Niger country name'},
  countryNG: {id: 'country.NG', defaultMessage: 'Nigeria', description: 'Nigeria country name'},
  countryNU: {id: 'country.NU', defaultMessage: 'Niue', description: 'Niue country name'},
  countryNF: {id: 'country.NF', defaultMessage: 'Norfolk Island', description: 'Norfolk Island country name'},
  countryMP: {
    id: 'country.MP',
    defaultMessage: 'Northern Mariana Islands',
    description: 'Northern Mariana Islands country name',
  },
  countryNO: {id: 'country.NO', defaultMessage: 'Norway', description: 'Norway country name'},
  countryOM: {id: 'country.OM', defaultMessage: 'Oman', description: 'Oman country name'},
  countryPK: {id: 'country.PK', defaultMessage: 'Pakistan', description: 'Pakistan country name'},
  countryPW: {id: 'country.PW', defaultMessage: 'Palau', description: 'Palau country name'},
  countryPS: {
    id: 'country.PS',
    defaultMessage: 'Palestinian Territories',
    description: 'Palestinian Territories country name',
  },
  countryPA: {id: 'country.PA', defaultMessage: 'Panama', description: 'Panama country name'},
  countryPG: {id: 'country.PG', defaultMessage: 'Papua New Guinea', description: 'Papua New Guinea country name'},
  countryPY: {id: 'country.PY', defaultMessage: 'Paraguay', description: 'Paraguay country name'},
  countryPE: {id: 'country.PE', defaultMessage: 'Peru', description: 'Peru country name'},
  countryPH: {id: 'country.PH', defaultMessage: 'Philippines', description: 'Philippines country name'},
  countryPN: {id: 'country.PN', defaultMessage: 'Pitcairn Islands', description: 'Pitcairn Islands country name'},
  countryPL: {id: 'country.PL', defaultMessage: 'Poland', description: 'Poland country name'},
  countryPT: {id: 'country.PT', defaultMessage: 'Portugal', description: 'Portugal country name'},
  countryPR: {id: 'country.PR', defaultMessage: 'Puerto Rico', description: 'Puerto Rico country name'},
  countryQA: {id: 'country.QA', defaultMessage: 'Qatar', description: 'Qatar country name'},
  countryRE: {id: 'country.RE', defaultMessage: 'Réunion', description: 'Réunion country name'},
  countryRO: {id: 'country.RO', defaultMessage: 'Romania', description: 'Romania country name'},
  countryRU: {id: 'country.RU', defaultMessage: 'Russia', description: 'Russia country name'},
  countryRW: {id: 'country.RW', defaultMessage: 'Rwanda', description: 'Rwanda country name'},
  countryBL: {id: 'country.BL', defaultMessage: 'St. Barthélemy', description: 'St. Barthélemy country name'},
  countrySH: {id: 'country.SH', defaultMessage: 'St. Helena', description: 'St. Helena country name'},
  countryKN: {id: 'country.KN', defaultMessage: 'St. Kitts & Nevis', description: 'St. Kitts & Nevis country name'},
  countryLC: {id: 'country.LC', defaultMessage: 'St. Lucia', description: 'St. Lucia country name'},
  countryMF: {id: 'country.MF', defaultMessage: 'St. Martin (France)', description: 'St. Martin (France) country name'},
  countryPM: {
    id: 'country.PM',
    defaultMessage: 'St. Pierre and Miquelon',
    description: 'St. Pierre and Miquelon country name',
  },
  countryVC: {
    id: 'country.VC',
    defaultMessage: 'St. Vincent and the Grenadines',
    description: 'St. Vincent and the Grenadines country name',
  },
  countryWS: {id: 'country.WS', defaultMessage: 'Samoa', description: 'Samoa country name'},
  countrySM: {id: 'country.SM', defaultMessage: 'San Marino', description: 'San Marino country name'},
  countryST: {id: 'country.ST', defaultMessage: 'São Tomé & Príncipe', description: 'São Tomé & Príncipe country name'},
  countrySA: {id: 'country.SA', defaultMessage: 'Saudi Arabia', description: 'Saudi Arabia country name'},
  countrySN: {id: 'country.SN', defaultMessage: 'Senegal', description: 'Senegal country name'},
  countryRS: {id: 'country.RS', defaultMessage: 'Serbia', description: 'Serbia country name'},
  countrySC: {id: 'country.SC', defaultMessage: 'Seychelles', description: 'Seychelles country name'},
  countrySL: {id: 'country.SL', defaultMessage: 'Sierra Leone', description: 'Sierra Leone country name'},
  countrySG: {id: 'country.SG', defaultMessage: 'Singapore', description: 'Singapore country name'},
  countryNL_BQ3: {id: 'country.NL_BQ3', defaultMessage: 'Sint Eustatius', description: 'Sint Eustatius country name'},
  countrySX: {id: 'country.SX', defaultMessage: 'Sint Maarten', description: 'Sint Maarten country name'},
  countrySK: {id: 'country.SK', defaultMessage: 'Slovakia', description: 'Slovakia country name'},
  countrySI: {id: 'country.SI', defaultMessage: 'Slovenia', description: 'Slovenia country name'},
  countrySB: {id: 'country.SB', defaultMessage: 'Solomon Islands', description: 'Solomon Islands country name'},
  countrySO: {id: 'country.SO', defaultMessage: 'Somalia', description: 'Somalia country name'},
  countryZA: {id: 'country.ZA', defaultMessage: 'South Africa', description: 'South Africa country name'},
  countryGS: {
    id: 'country.GS',
    defaultMessage: 'South Georgia & South Sandwich Islands',
    description: 'South Georgia & South Sandwich Islands country name',
  },
  countryGE_SO: {id: 'country.GE_SO', defaultMessage: 'South Ossetia', description: 'South Ossetia country name'},
  countrySS: {id: 'country.SS', defaultMessage: 'South Sudan', description: 'South Sudan country name'},
  countryES: {id: 'country.ES', defaultMessage: 'Spain', description: 'Spain country name'},
  countryLK: {id: 'country.LK', defaultMessage: 'Sri Lanka', description: 'Sri Lanka country name'},
  countrySD: {id: 'country.SD', defaultMessage: 'Sudan', description: 'Sudan country name'},
  countrySR: {id: 'country.SR', defaultMessage: 'Suriname', description: 'Suriname country name'},
  countrySJ_NO: {id: 'country.SJ_NO', defaultMessage: 'Svalbard', description: 'Svalbard country name'},
  countrySZ: {id: 'country.SZ', defaultMessage: 'Swaziland', description: 'Swaziland country name'},
  countrySE: {id: 'country.SE', defaultMessage: 'Sweden', description: 'Sweden country name'},
  countryCH: {id: 'country.CH', defaultMessage: 'Switzerland', description: 'Switzerland country name'},
  countrySY: {id: 'country.SY', defaultMessage: 'Syria', description: 'Syria country name'},
  countryTW: {id: 'country.TW', defaultMessage: 'Taiwan', description: 'Taiwan country name'},
  countryTJ: {id: 'country.TJ', defaultMessage: 'Tajikistan', description: 'Tajikistan country name'},
  countryTZ: {id: 'country.TZ', defaultMessage: 'Tanzania', description: 'Tanzania country name'},
  countryTH: {id: 'country.TH', defaultMessage: 'Thailand', description: 'Thailand country name'},
  countryTG: {id: 'country.TG', defaultMessage: 'Togo', description: 'Togo country name'},
  countryTK: {id: 'country.TK', defaultMessage: 'Tokelau', description: 'Tokelau country name'},
  countryTO: {id: 'country.TO', defaultMessage: 'Tonga', description: 'Tonga country name'},
  countryTT: {id: 'country.TT', defaultMessage: 'Trinidad & Tobago', description: 'Trinidad & Tobago country name'},
  countryTN: {id: 'country.TN', defaultMessage: 'Tunisia', description: 'Tunisia country name'},
  countryTR: {id: 'country.TR', defaultMessage: 'Turkey', description: 'Turkey country name'},
  countryTM: {id: 'country.TM', defaultMessage: 'Turkmenistan', description: 'Turkmenistan country name'},
  countryTC: {
    id: 'country.TC',
    defaultMessage: 'Turks & Caicos Islands',
    description: 'Turks & Caicos Islands country name',
  },
  countryTV: {id: 'country.TV', defaultMessage: 'Tuvalu', description: 'Tuvalu country name'},
  countryUG: {id: 'country.UG', defaultMessage: 'Uganda', description: 'Uganda country name'},
  countryUA: {id: 'country.UA', defaultMessage: 'Ukraine', description: 'Ukraine country name'},
  countryAE: {
    id: 'country.AE',
    defaultMessage: 'United Arab Emirates',
    description: 'United Arab Emirates country name',
  },
  countryUK: {id: 'country.UK', defaultMessage: 'United Kingdom', description: 'United Kingdom country name'},
  countryUS: {id: 'country.US', defaultMessage: 'United States', description: 'United States country name'},
  countryUY: {id: 'country.UY', defaultMessage: 'Uruguay', description: 'Uruguay country name'},
  countryVI: {id: 'country.VI', defaultMessage: 'U.S. Virgin Islands', description: 'U.S. Virgin Islands country name'},
  countryUZ: {id: 'country.UZ', defaultMessage: 'Uzbekistan', description: 'Uzbekistan country name'},
  countryVU: {id: 'country.VU', defaultMessage: 'Vanuatu', description: 'Vanuatu country name'},
  countryVE: {id: 'country.VE', defaultMessage: 'Venezuela', description: 'Venezuela country name'},
  countryVA: {id: 'country.VA', defaultMessage: 'Vatican City', description: 'Vatican City country name'},
  countryVN: {id: 'country.VN', defaultMessage: 'Vietnam', description: 'Vietnam country name'},
  countryWF: {id: 'country.WF', defaultMessage: 'Wallis & Futuna', description: 'Wallis & Futuna country name'},
  countryYE: {id: 'country.YE', defaultMessage: 'Yemen', description: 'Yemen country name'},
  countryZM: {id: 'country.ZM', defaultMessage: 'Zambia', description: 'Zambia country name'},
  countryTZ_UK: {id: 'country.TZ_UK', defaultMessage: 'Zanzibar', description: 'Zanzibar country name'},
  countryZW: {id: 'country.ZW', defaultMessage: 'Zimbabwe', description: 'Zimbabwe country name'},
};